#define CMYREFLECTION_REFLECTION_TYPES TYPE_VECTOR2, TYPE_GAMEOBJECT,
#define CMYREFLECTION_IMPLEMENTATION
#include "../cmyreflection.h"
#include <stdio.h>

// 1. Define custom struct
typedef struct
{
    float x, y;
} Vector2;

// 2. Inject custom types into the enum

// 4. Generate the safe wrapper: creates set_field_vec2()
DEFINE_FIELD_SETTER(vec2, TYPE_VECTOR2, Vector2);

// --- Example Usage ---

// Generated by your python script:
const FieldInfo Player_Metadata[] = {
    {"position", TYPE_VECTOR2, 0, sizeof(Vector2)} // Note the sizeof!
};

int main()
{
    struct
    {
        Vector2 position;
    } my_player = {0};

    // Safely assign the custom type
    Vector2 new_pos = {10.5f, 20.0f};
    set_field_vec2(&my_player, &Player_Metadata[0], new_pos);

    printf("Player pos: %.1f, %.1f\n", my_player.position.x,
           my_player.position.y);
    return 0;
}
