Could not open file .\test\mocks\game_type.c

/*
* Auto Generated by CMyReflection python script
* Version 0.0.0
*/
// clang-format off

#define CMYREFLECTION_PARSED
#ifndef _CMYREFLECTION_AUTOGEN
#define _CMYREFLECTION_AUTOGEN
typedef enum {
    TYPE_CHAR,
    TYPE_DAMAGE_COMPONENT,
    TYPE_FLOAT,
    TYPE_INT,
    TYPE_STR,
    TYPE_UNKNOWN,
} FieldType;

#include <cmyreflection.h>
// --- Metadata Declarations
extern const FieldInfo DamageComponent_Metadata[];
extern const size_t DamageComponent_FieldCount;

DEFINE_FIELD_SETTER(int, TYPE_INT, int)
DEFINE_FIELD_SETTER(float, TYPE_FLOAT, float)
DEFINE_FIELD_SETTER(char, TYPE_CHAR, char)
DEFINE_FIELD_SETTER(str, TYPE_STR, char*)
DEFINE_FIELD_SETTER(conststr, TYPE_STR, constchar*)
DEFINE_FIELD_SETTER(DamageComponent, TYPE_DAMAGE_COMPONENT, DamageComponent)

#endif // _CMYREFLECTION_AUTOGEN
// --- Metadata Definitions
#ifdef REFLECTION_IMPLEMENTATION

// --- Generated from .\test\mocks\stuff.h ---
const FieldInfo DamageComponent_Metadata[] = {
    { "damage", TYPE_FLOAT, offsetof(DamageComponent, damage), sizeof(float) },
};
const size_t DamageComponent_FieldCount = sizeof(DamageComponent_Metadata) / sizeof(FieldInfo);

#endif // REFLECTION_IMPLEMENTATION
