/*
* Auto Generated by CMyReflection python script
* Version 0.0.0
*/
// clang-format off

#define CMYREFLECTION_PARSED
#ifndef CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_REGISTRY
typedef enum {
    TYPE_CHAR,
    TYPE_CHAR_ARR,
    TYPE_CHAR_PTR,
    TYPE_POST,
    TYPE_POST_PTR,
    TYPE_SIZE_T,
    TYPE_STRUCT_USER,
    TYPE_UNKNOWN,
} FieldType;

#include <cmyreflection.h>

/*
 * CMyReflection Active Plugins
 *  -> Printer (v0.0.0) by oonamo - Provides run time printing for primitive types
 *    - Provides tag: @no_print (Enums) - Forces the plugin to not generate get_field_as_str for enum
 *    - Provides tag: @format(value) (Struct Fields) - Specify a C format specifier for a struct.
 *      Does not create a get_field_as_str function if not defined
 *      Example:
 *      +  @format("struct MyStruct @ addr: %p")
 *      +  typedef struct { ... } MyStruct;
 *    - Provides tag: @display(value) (Enum Members) - Specifies how an enum should be displayed.
 *      Defaults to name of the enum member if not provided
 *      Example:
 *      +  @display("enum a")
 *      +  ENUM_A
 *    - Provides macro: CMY_HAS_PRINTER_PLUGIN (Value: 1) - Printer plugin is available
 *    - Provides macro: CMY_PLUGIN_PRINTER_ENABLED (Default: 1) - Enables the Printer plugin
 *    - Provides macro: CMY_PRINTER_MAX_BUF_LEN (Default: 256) - Default buffer len for printing (_MSC_VER)
 *    - Provides macro: CMY_PRINTF (Default: printf) - Defines the printf implementation
 *    - Provides router: ReflectResult get_field_as_str(..) - Creates a get_type_as_str for the type for primitives and enums
 *      By default, enums are enabled
 *      + Types: char_arr, char, char*, size_t
 *    - Provides function: ReflectResult print_field(...) - Prints a field, if it implements get_field_as_str
 *  -> json (v0.0.1) by oonamo - A json serializer plugin
 *    - Provides tag: @json_serialize_function(value) (Structs) - Function to call to serialize this type
 *      Example:
 *      +  @json_serialize_function(MyCoolStruct_Serializer)
 *      +  typedef enum { ... } MyCoolStruct;
 *      +  // in a seperate file
 *      +  #include "reflection.h"
 *      +  void MyCoolStruct_Serializer(const void* instance, const StructFieldInfo* field, _cmy_json_state* state);
 *    - Provides tag: @json_serialize_function(value) (Enums) - Function to call to serialize this type
 *      Example:
 *      +  @json_serialize_function(MyCoolEnum_Serializer)
 *      +  typedef enum { ... } MyCoolEnum;
 *      +  // in a seperate file
 *      +  #include "reflection.h"
 *      +  void MyCoolEnum_Serializer(const void* instance, const StructFieldInfo* field, _cmy_json_state* state);
 *    - Provides macro: CMY_HAS_JSON_PLUGIN (Value: 1) - json plugin is available
 *    - Provides macro: CMY_PLUGIN_JSON_ENABLED (Default: 1) - Enables the json plugin
 *    - Provides router: ReflectResult json_serialize_custom(..) - Process fields dynamically based on their type
 (No types mapped)
 *    - Provides router: bool json_is_string_type(..) - Checks if a type represents a string
 *      + Types: char_arr, char*
 *    - Provides router: bool json_needs_quote(..) - Dynamically determines if the type requires JSON quotes
 *      + Types: char_arr, char*
 *    - Provides function: void _json_traversal_iterator(...) - Json Traversal serializer
 *    - Provides function: void json_serialize_value(...) - Serialize a value into valid json
 *    - Provides function: ReflectResult to_json(...) - Converts a given type to a json string
 */


// ----------------------------------------
// Generated by 'json'
// ----------------------------------------
typedef struct
{
    int indent;
    bool is_first_field;
    FIELD_TYPE current_parent_type;

    char* _buf;
    size_t _max_len;
    size_t _current_offset;
} _cmy_json_state;

#define CMY_JSON_WRITE(state_ptr, fmt, ...)                               \
        do {                                                              \
            if ((state_ptr)->_current_offset < (state_ptr)->_max_len) {   \
                (state_ptr)->_current_offset += snprintf(                 \
                    (state_ptr)->_buf + (state_ptr)->_current_offset,     \
                    (state_ptr)->_max_len - (state_ptr)->_current_offset, \
                    fmt, ##__VA_ARGS__);                                  \
            }                                                             \
        } while(0);


#define CMY_HAS_PRINTER_PLUGIN 1
#ifndef CMY_PLUGIN_PRINTER_ENABLED
#    define CMY_PLUGIN_PRINTER_ENABLED 1
#endif //CMY_PLUGIN_PRINTER_ENABLED
#ifndef CMY_PRINTER_MAX_BUF_LEN
#    define CMY_PRINTER_MAX_BUF_LEN 256
#endif //CMY_PRINTER_MAX_BUF_LEN
#ifndef CMY_PRINTF
#    define CMY_PRINTF printf
#endif //CMY_PRINTF
#define CMY_HAS_JSON_PLUGIN 1
#ifndef CMY_PLUGIN_JSON_ENABLED
#    define CMY_PLUGIN_JSON_ENABLED 1
#endif //CMY_PLUGIN_JSON_ENABLED


// ########################################
// Printer Declarations
// ########################################
#ifdef CMY_PLUGIN_PRINTER_ENABLED
static inline  ReflectResult get_field_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline  ReflectResult get_field_char_arr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline  ReflectResult get_field_char_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline  ReflectResult get_field_size_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline  ReflectResult get_field_str_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline  ReflectResult print_field(const void* instance, const StructFieldInfo* field);
#endif // CMY_PLUGIN_PRINTER_ENABLED

// ########################################
// json Declarations
// ########################################
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline  void _json_traversal_iterator(const void            *base_instance,
                             const StructFieldInfo  *field,
                             void                   *user_data);
static inline  bool json_is_string_type(FIELD_TYPE type);
static inline  bool json_needs_quote(FIELD_TYPE type);
static inline  ReflectResult json_serialize_custom(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state);
static inline  void json_serialize_value(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state);
static inline  ReflectResult to_json(const void* instance, FIELD_TYPE root_type, char* out_buf, size_t buflen);
#endif // CMY_PLUGIN_JSON_ENABLED


#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
typedef struct {
#ifdef CMY_PLUGIN_PRINTER_ENABLED
     const char* format;
#endif // CMY_PLUGIN_PRINTER_ENABLED
} StructFieldExtension;

typedef struct {
#ifdef CMY_PLUGIN_PRINTER_ENABLED
     const char* display;
#endif // CMY_PLUGIN_PRINTER_ENABLED
} EnumMemberExtension;
// --- Metadata Declarations
extern const StructFieldInfo User_Metadata[];
extern const size_t User_FieldCount;

#define GET_FIELD_EXT(field_ptr) \
    ((field_ptr) && (field_ptr)->user_data ? (const StructFieldExtension*)((field_ptr)->user_data) : NULL)

#define GET_MEMBER_EXT(member_ptr) \
    ((member_ptr) && (member_ptr)->user_data ? ((const EnumMemberExtension*)(member_ptr->user_data)) : NULL)

// --- Auto-Generated Enum Validators ---
DEFINE_FIELD_SETTER(User, TYPE_STRUCT_USER, User)
DEFINE_FIELD_GETTER(User, TYPE_STRUCT_USER, User)

DEFINE_ARRAY_SETTER(char_arr, TYPE_CHAR_ARR, char *, char)
DEFINE_ARRAY_GETTER(char_arr, TYPE_CHAR_ARR, char *, char)

DEFINE_FIELD_SETTER(char, TYPE_CHAR, char)
DEFINE_FIELD_GETTER(char, TYPE_CHAR, char)

DEFINE_FIELD_SETTER(str, TYPE_CHAR_PTR, char*)
DEFINE_FIELD_GETTER(str, TYPE_CHAR_PTR, char*)

DEFINE_FIELD_SETTER(size_t, TYPE_SIZE_T, size_t)
DEFINE_FIELD_GETTER(size_t, TYPE_SIZE_T, size_t)

DEFINE_FIELD_SETTER(Post_ptr, TYPE_POST_PTR, Post *)
DEFINE_FIELD_GETTER(Post_ptr, TYPE_POST_PTR, Post *)

DEFINE_FIELD_SETTER(Post, TYPE_POST, Post)
DEFINE_FIELD_GETTER(Post, TYPE_POST, Post)

DEFINE_DYNAMIC_ARRAY_SETTER(User_posts, TYPE_POST_PTR, Post *, Post, TYPE_STRUCT_USER)
DEFINE_DYNAMIC_ARRAY_GETTER(User_posts, TYPE_POST_PTR, Post *, Post)

// --- Plugin-Generated-Extensions ---

// ==========================================
// Plugin: Printer
// ==========================================
#ifdef CMY_PLUGIN_PRINTER_ENABLED
static inline ReflectResult print_field(const void* instance, const StructFieldInfo* field)
{
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

#ifdef _MSC_VER
    size_t buflen = CMY_PRINTER_MAX_BUF_LEN;
    char buf[CMY_PRINTER_MAX_BUF_LEN];
#else // May have VLA support
    size_t buflen = field->count > 256 ? field->count : 256;
    char buf[buflen];
#endif

    ReflectResult res = get_field_as_str(instance, field, buf, buflen);
    if (res != REFLECT_OK) {
        return res;
    }

    CMY_PRINTF("%s", buf);
    return REFLECT_OK;
}

#endif // CMY_PLUGIN_PRINTER_ENABLED
#ifdef CMY_PLUGIN_PRINTER_ENABLED
static inline ReflectResult get_field_char_arr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) {
        return REFLECT_ERR_NULL_PTR;
    }

    #ifdef _MSC_VER
        char var[CMY_PRINTER_MAX_BUF_LEN];;
        size_t arr_len = CMY_PRINTER_MAX_BUF_LEN;
    #else
        char var[field->count];
        size_t arr_len = field->count;
    #endif

    ReflectResult res = get_field_char_arr(instance, field, var, arr_len);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_char_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    char var;
    ReflectResult res = get_field_char(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%c";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_str_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    char* var;
    ReflectResult res = get_field_str(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_size_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    size_t var;
    ReflectResult res = get_field_size_t(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%zu";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!field) { return REFLECT_ERR_NULL_PTR; }
    switch(field->type) {
        case TYPE_CHAR_ARR: return get_field_char_arr_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR: return get_field_char_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR_PTR: return get_field_str_as_str(instance, field, out_buf, buflen);
        case TYPE_SIZE_T: return get_field_size_t_as_str(instance, field, out_buf, buflen);
        default: return REFLECT_ERR_TYPE_MISMATCH;
    }
}

#endif // CMY_PLUGIN_PRINTER_ENABLED

// ==========================================
// Plugin: json
// ==========================================
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void json_serialize_value(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state)
{
    if (json_serialize_custom(exact_data_ptr, actual_type, field_ctx, state) == REFLECT_OK)
    {
        return;
    }

    StructMetaData meta;
    if (get_struct_metadata(actual_type, &meta) == REFLECT_OK) {
        CMY_JSON_WRITE(state, "{\n");

        _cmy_json_state nested_state = *state;
        nested_state.indent += 4;
        nested_state.is_first_field = true;
        nested_state.current_parent_type = actual_type;

        visit_struct_fields(exact_data_ptr, actual_type, _json_traversal_iterator, &nested_state);

        state->_current_offset = nested_state._current_offset;
        CMY_JSON_WRITE(state, "\n%*s}", state->indent + 4, "");
        return;
    }

    char val_buf[256] = "null";
    if (exact_data_ptr) {
        StructFieldInfo element_field = *field_ctx;
        element_field.type = actual_type;
        element_field.offset = 0;

        if (!json_is_string_type(actual_type)) {
            element_field.count = 1;
        }

        if (get_field_as_str(exact_data_ptr, &element_field, val_buf, sizeof(val_buf)) != REFLECT_OK) {
            snprintf(val_buf, sizeof(val_buf), "%s", "could not get type as str");
        }
    } else {
        snprintf(val_buf, sizeof(val_buf), "%s", get_name_of_type(actual_type));
    }

    if (!exact_data_ptr || json_needs_quote(actual_type)) {
        CMY_JSON_WRITE(state, "\"%s\"", val_buf);
    } else {
        CMY_JSON_WRITE(state, "%s", val_buf);
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void _json_traversal_iterator(const void            *base_instance,
                             const StructFieldInfo  *field,
                             void                   *user_data)
{
    if (!field || !(field->flags & FIELD_ACCESS_READ)) { return; }

    _cmy_json_state *state = (_cmy_json_state*)user_data;
    if (!state->is_first_field) {
        CMY_JSON_WRITE(state, ",\n");
    } else {
        state->is_first_field = false;
    }

    // Print Key
    CMY_JSON_WRITE(state, "%*s\"%s\": ", state->indent + 4, "", field->name);

    bool is_string = json_is_string_type(field->type);
    bool is_dynamic = field->length_field_name != NULL;
    bool is_arr = (is_dynamic || (field->count > 1)) && !is_string;

    if (is_arr) {
        if (!base_instance) {
            const char* type_name = get_name_of_type(get_base_type(field->type));
            if (is_dynamic) {
                CMY_JSON_WRITE(state, "[\"%s (dynamic: %s)\"]", type_name, field->length_field_name);
            } else if (is_arr) {
                CMY_JSON_WRITE(state, "[\"%s (max: %zu)\"]", type_name, field->count);
            }
            return;
        }

        size_t array_len = 0;
        const void* array_ptr = NULL;
        FIELD_TYPE base_type = get_base_type(field->type);
        size_t base_size = get_type_size(base_type);

        if (is_dynamic) {
            if (get_dynamic_array_length(base_instance, state->current_parent_type, field, &array_len) != REFLECT_OK) {
                CMY_JSON_WRITE(state, "null");
                return;
            }
            if (get_field_value(base_instance, field, (void*)&array_ptr, sizeof(void*)) != REFLECT_OK)
            {
                CMY_JSON_WRITE(state, "null");
                return;
            }
        } else {
            array_len = field->count;
            array_ptr = (const char*)base_instance + field->offset;
        }

        CMY_JSON_WRITE(state, "[\n");
        _cmy_json_state arr_state = *state;
        arr_state.indent += 4;
        for (size_t i = 0; i < array_len; i++)
        {
            CMY_JSON_WRITE(&arr_state, "%*s", arr_state.indent + 4, "");
            void* ith_element = (char*)array_ptr + (i * base_size);

            if (!ith_element) {
                CMY_JSON_WRITE(&arr_state, "null");
            } else {
                json_serialize_value(ith_element, base_type, field, &arr_state);
            }

            if (i < array_len - 1) {
                CMY_JSON_WRITE(&arr_state, ",\n");
            } else {
                CMY_JSON_WRITE(&arr_state, "\n");
            }
        }
        state->_current_offset = arr_state._current_offset;
        CMY_JSON_WRITE(state, "%*s]", state->indent + 4, "");

        return;
    } else {
        const void* data_ptr = base_instance ? ((const char*)base_instance + field->offset) : NULL;
        json_serialize_value(data_ptr, field->type, field, state);
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline ReflectResult to_json(const void* instance, FIELD_TYPE root_type, char* out_buf, size_t buflen)
{
    if (!out_buf || buflen == 0) { return REFLECT_ERR_NULL_PTR; }
    _cmy_json_state state = {
        .indent = 0,
        .is_first_field = true,
        .current_parent_type = root_type,
        ._buf = out_buf,
        ._max_len = buflen,
        ._current_offset = 0,
    };

    CMY_JSON_WRITE(&state, "{\n");

    visit_struct_fields(instance, root_type, _json_traversal_iterator, &state);

    CMY_JSON_WRITE(&state, "\n}");

    return REFLECT_OK;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline ReflectResult json_serialize_custom(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state) {
    
    return REFLECT_ERR_TYPE_MISMATCH;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline bool json_is_string_type(FIELD_TYPE type) {
    
    switch(type) {
        case TYPE_CHAR_ARR: return true;
        case TYPE_CHAR_PTR: return true;
        default: return false;
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline bool json_needs_quote(FIELD_TYPE type) {
    
    switch(type) {
        case TYPE_CHAR_ARR: return true;
        case TYPE_CHAR_PTR: return true;
        default: return false;
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED

#endif // CMYREFLECTION_AUTOGEN_H
// --- Metadata Definitions
#ifdef REFLECTION_IMPLEMENTATION

// --- Generated from test_json_types.h ---
const StructFieldInfo User_Metadata[] = {
    { "username", TYPE_CHAR_ARR, offsetof(User, username), sizeof(char[64]), 64, FIELD_ACCESS_RW, NULL, NULL },
    { "email", TYPE_CHAR_ARR, offsetof(User, email), sizeof(char[64]), 64, FIELD_ACCESS_RW, NULL, NULL },
    { "bio", TYPE_CHAR_PTR, offsetof(User, bio), sizeof(char*), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "password_hash", TYPE_CHAR_ARR, offsetof(User, password_hash), sizeof(char[16]), 16, FIELD_ACCESS_WRITE, NULL, NULL },
    { "post_count", TYPE_SIZE_T, offsetof(User, post_count), sizeof(size_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "posts", TYPE_POST_PTR, offsetof(User, posts), sizeof(Post *), 1, FIELD_ACCESS_RW, "post_count", NULL },
};
const size_t User_FieldCount = sizeof(User_Metadata) / sizeof(StructFieldInfo);

// --- Auto-Generated Type Registry
ReflectResult get_struct_metadata(FieldType type, StructMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_STRUCT_USER:
          out_meta->fields = User_Metadata;
          out_meta->count = User_FieldCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated Type Registry
ReflectResult get_enum_metadata(FieldType type, EnumMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {

        default: return REFLECT_ERR_ENUM_INVALID;
    }
}


// --- Auto-Generated Safe Type Setter
ReflectResult safe_set_field(void* instance, const StructFieldInfo* field, const void* value, size_t element_count) {
    if (!instance || !field || !value) return false;
    switch(field->type) {
      case TYPE_STRUCT_USER: return set_field_User(instance, field, *(User*)value);
      case TYPE_CHAR_ARR: return set_field_char_arr(instance, field, (char*)value, element_count);
      case TYPE_CHAR: return set_field_char(instance, field, *(char*)value);
      case TYPE_CHAR_PTR: return set_field_str(instance, field, *(char**)value);
      case TYPE_SIZE_T: return set_field_size_t(instance, field, *(size_t*)value);
      case TYPE_POST_PTR: return set_field_Post_ptr(instance, field, *(Post **)value);
      case TYPE_POST: return set_field_Post(instance, field, *(Post*)value);
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated enum->name converter
const char* get_name_of_type(FieldType type) {
    switch(type) {
     case TYPE_CHAR: return "TYPE_CHAR";
     case TYPE_CHAR_ARR: return "TYPE_CHAR_ARR";
     case TYPE_CHAR_PTR: return "TYPE_CHAR_PTR";
     case TYPE_POST: return "TYPE_POST";
     case TYPE_POST_PTR: return "TYPE_POST_PTR";
     case TYPE_SIZE_T: return "TYPE_SIZE_T";
     case TYPE_STRUCT_USER: return "TYPE_STRUCT_USER";
     case TYPE_UNKNOWN: return "TYPE_UNKNOWN";
        default: return NULL;
    };
}

FieldType get_base_type(FieldType type) {
    switch(type) {
      case TYPE_CHAR_ARR: return TYPE_CHAR;
      case TYPE_CHAR_PTR: return TYPE_CHAR;
      case TYPE_POST_PTR: return TYPE_POST;
        default: return type;
    }
}

size_t get_type_size(FIELD_TYPE type) {
    switch(type) {
        case TYPE_STRUCT_USER: return sizeof(User);
        case TYPE_CHAR_ARR: return sizeof(char *);
        case TYPE_CHAR: return sizeof(char);
        case TYPE_CHAR_PTR: return sizeof(char*);
        case TYPE_SIZE_T: return sizeof(size_t);
        case TYPE_POST_PTR: return sizeof(Post *);
        case TYPE_POST: return sizeof(Post);
        default: return 0;
    }
}
#endif // REFLECTION_IMPLEMENTATION

