/*
* Auto Generated by CMyReflection python script
* Version 0.0.0
*
* USAGE:
* In EXACTLY ONE .c file, set up the implementations
*   #include "your_types.h"
*   #define CMYREFLECTION_IMPLEMENTATION
*   #define REFLECTION_IMPLEMENTATION
*   #include "this_generated_file.h"
*/

#ifdef _MSC_VER
   #pragma warning(push)
   #pragma warning(disable : 4996)
#endif
#define CMYREFLECTION_PARSED
#ifndef CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_REGISTRY
typedef enum {
    TYPE_CHAR,
    TYPE_CHAR_ARR,
    TYPE_CHAR_PTR,
    TYPE_CONSTCHAR,
    TYPE_CONSTCHAR_PTR,
    TYPE_DOUBLE,
    TYPE_ENUM_ENUMTYPE,
    TYPE_FLOAT,
    TYPE_INT,
    TYPE_INT16_T,
    TYPE_INT32_T,
    TYPE_INT64_T,
    TYPE_INT8_T,
    TYPE_LONG,
    TYPE_SHORT,
    TYPE_STRUCT_MOCKSTRUCT,
    TYPE_STRUCT_NUMTYPES,
    TYPE_STRUCT_SPECIFIED,
    TYPE_STRUCT_STRINGTYPE,
    TYPE_UINT16_T,
    TYPE_UINT32_T,
    TYPE_UINT64_T,
    TYPE_UINT8_T,
    TYPE_UNKNOWN,
    TYPE_UNSIGNEDCHAR,
    TYPE_UNSIGNEDINT,
    TYPE_UNSIGNEDLONG,
    TYPE_UNSIGNEDSHORT,
} FieldType;

#include <cmyreflection.h>

/*
 * CMyReflection Active Plugins
 *  -> format (v0.0.0) by oonamo - Provides run time printing for primitive types
 *    - Provides tag: @no_print (Enums) - Forces the plugin to not generate get_field_as_str for enum
 *    - Provides tag: @format(value) (Struct Fields) - Specify a C format specifier for a struct.
 *      Does not create a get_field_as_str function if not defined
 *      Example:
 *      +  typedef struct {
 *      +      // cmy:format("my type: %x")
 *      +      int x;
 *      +  } MyStruct;
 *    - Provides tag: @display(value) (Enum Members) - Specifies how an enum should be displayed.
 *      Defaults to name of the enum member if not provided
 *      Example:
 *      +  typedef enum {
 *      +      // cmy:display("enum a")
 *      +      ENUM_A,
 *      +  } MyEnum;
 *    - Provides macro: CMY_HAS_FORMAT_PLUGIN (Value: 1) - format plugin is available
 *    - Provides macro: CMY_PLUGIN_FORMAT_ENABLED (Default: 1) - Enables the format plugin
 *    - Provides macro: CMY_FORMAT_MAX_BUF_LEN (Default: 256) - Default buffer len for printing (_MSC_VER)
 *    - Provides macro: CMY_PRINTF (Default: printf) - Defines the printf implementation
 *    - Provides router: ReflectResult get_field_as_str(..) - Creates a get_type_as_str for the type for primitives and enums
 *      By default, enums are enabled
 *      + Types: EnumType, char*, char, char_arr, constchar*, int, unsignedint,
 *        short, unsignedshort, long, unsignedlong, unsignedchar, float, double,
 *        uint8_t, uint16_t, uint32_t, uint64_t, int8_t, int16_t, int32_t,
 *        int64_t
 *    - Provides function: ReflectResult print_field(...) - Prints a field, if it implements get_field_as_str
 */

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>

#define CMY_HAS_FORMAT_PLUGIN 1
#ifndef CMY_PLUGIN_FORMAT_ENABLED
#    define CMY_PLUGIN_FORMAT_ENABLED 1
#endif //CMY_PLUGIN_FORMAT_ENABLED
#ifndef CMY_FORMAT_MAX_BUF_LEN
#    define CMY_FORMAT_MAX_BUF_LEN 256
#endif //CMY_FORMAT_MAX_BUF_LEN
#ifndef CMY_PRINTF
#    define CMY_PRINTF printf
#endif //CMY_PRINTF


// ########################################
// format Declarations
// ########################################
#ifdef CMY_PLUGIN_FORMAT_ENABLED
static inline ReflectResult get_field_EnumType_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_char_arr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_char_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_conststr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_double_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_float_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_int16_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_int32_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_int64_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_int8_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_int_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_long_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_short_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_str_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_u16_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_u32_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_u64_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_u8_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_uint_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_unsignedchar_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_unsignedlong_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_unsignedshort_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult print_field(const void* instance, const StructFieldInfo* field);
#endif // CMY_PLUGIN_FORMAT_ENABLED


typedef struct {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
     const char* format;
#endif // CMY_PLUGIN_FORMAT_ENABLED
} StructFieldExtension;

typedef struct {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
     const char* display;
#endif // CMY_PLUGIN_FORMAT_ENABLED
} EnumMemberExtension;
// --- Metadata Declarations
extern const StructFieldInfo StringType_Metadata[];
extern const size_t StringType_FieldCount;
extern const StructFieldInfo NumTypes_Metadata[];
extern const size_t NumTypes_FieldCount;
extern const StructFieldInfo MockStruct_Metadata[];
extern const size_t MockStruct_FieldCount;
extern const StructFieldInfo Specified_Metadata[];
extern const size_t Specified_FieldCount;
extern const StructFieldExtension ext_Specified_as_hex;
extern const StructFieldExtension ext_Specified_with_prefix;
extern const StructFieldExtension ext_Specified_percent;
extern const EnumMemberInfo EnumType_Members[];
extern const size_t EnumType_MemberCount;
extern const EnumMemberExtension ext_EnumType_ENUM_ERR;

#define GET_FIELD_EXT(field_ptr) \
    ((field_ptr) && (field_ptr)->user_data ? (const StructFieldExtension*)((field_ptr)->user_data) : NULL)

#define GET_MEMBER_EXT(member_ptr) \
    ((member_ptr) && (member_ptr)->user_data ? ((const EnumMemberExtension*)(member_ptr->user_data)) : NULL)

// --- Auto-Generated Enum Validators ---

static inline bool is_valid_EnumType(EnumType value) {
    switch(value) {
      case ENUM_A:
      case ENUM_B:
      case ENUM_C:
      case ENUM_ERR:
           return true;
    default:
        return false;
    }
}

DEFINE_FIELD_SETTER(StringType, TYPE_STRUCT_STRINGTYPE, StringType)
DEFINE_FIELD_GETTER(StringType, TYPE_STRUCT_STRINGTYPE, StringType)

DEFINE_FIELD_SETTER(NumTypes, TYPE_STRUCT_NUMTYPES, NumTypes)
DEFINE_FIELD_GETTER(NumTypes, TYPE_STRUCT_NUMTYPES, NumTypes)

DEFINE_ENUM_SETTER(EnumType, TYPE_ENUM_ENUMTYPE, EnumType, is_valid_EnumType)
DEFINE_FIELD_GETTER(EnumType, TYPE_ENUM_ENUMTYPE, EnumType)

DEFINE_FIELD_SETTER(MockStruct, TYPE_STRUCT_MOCKSTRUCT, MockStruct)
DEFINE_FIELD_GETTER(MockStruct, TYPE_STRUCT_MOCKSTRUCT, MockStruct)

DEFINE_FIELD_SETTER(Specified, TYPE_STRUCT_SPECIFIED, Specified)
DEFINE_FIELD_GETTER(Specified, TYPE_STRUCT_SPECIFIED, Specified)

DEFINE_FIELD_SETTER(str, TYPE_CHAR_PTR, char *)
DEFINE_FIELD_GETTER(str, TYPE_CHAR_PTR, char *)

DEFINE_FIELD_SETTER(char, TYPE_CHAR, char)
DEFINE_FIELD_GETTER(char, TYPE_CHAR, char)

DEFINE_ARRAY_SETTER(char_arr, TYPE_CHAR_ARR, char *, char)
DEFINE_ARRAY_GETTER(char_arr, TYPE_CHAR_ARR, char *, char)

DEFINE_FIELD_SETTER(conststr, TYPE_CONSTCHAR_PTR, const char *)
DEFINE_FIELD_GETTER(conststr, TYPE_CONSTCHAR_PTR, const char *)

DEFINE_FIELD_SETTER(constchar, TYPE_CONSTCHAR, const char)
DEFINE_FIELD_GETTER(constchar, TYPE_CONSTCHAR, const char)

DEFINE_FIELD_SETTER(int, TYPE_INT, int)
DEFINE_FIELD_GETTER(int, TYPE_INT, int)

DEFINE_FIELD_SETTER(uint, TYPE_UNSIGNEDINT, unsigned int)
DEFINE_FIELD_GETTER(uint, TYPE_UNSIGNEDINT, unsigned int)

DEFINE_FIELD_SETTER(short, TYPE_SHORT, short)
DEFINE_FIELD_GETTER(short, TYPE_SHORT, short)

DEFINE_FIELD_SETTER(unsignedshort, TYPE_UNSIGNEDSHORT, unsigned short)
DEFINE_FIELD_GETTER(unsignedshort, TYPE_UNSIGNEDSHORT, unsigned short)

DEFINE_FIELD_SETTER(long, TYPE_LONG, long)
DEFINE_FIELD_GETTER(long, TYPE_LONG, long)

DEFINE_FIELD_SETTER(unsignedlong, TYPE_UNSIGNEDLONG, unsigned long)
DEFINE_FIELD_GETTER(unsignedlong, TYPE_UNSIGNEDLONG, unsigned long)

DEFINE_FIELD_SETTER(unsignedchar, TYPE_UNSIGNEDCHAR, unsigned char)
DEFINE_FIELD_GETTER(unsignedchar, TYPE_UNSIGNEDCHAR, unsigned char)

DEFINE_FIELD_SETTER(float, TYPE_FLOAT, float)
DEFINE_FIELD_GETTER(float, TYPE_FLOAT, float)

DEFINE_FIELD_SETTER(double, TYPE_DOUBLE, double)
DEFINE_FIELD_GETTER(double, TYPE_DOUBLE, double)

DEFINE_FIELD_SETTER(u8, TYPE_UINT8_T, uint8_t)
DEFINE_FIELD_GETTER(u8, TYPE_UINT8_T, uint8_t)

DEFINE_FIELD_SETTER(u16, TYPE_UINT16_T, uint16_t)
DEFINE_FIELD_GETTER(u16, TYPE_UINT16_T, uint16_t)

DEFINE_FIELD_SETTER(u32, TYPE_UINT32_T, uint32_t)
DEFINE_FIELD_GETTER(u32, TYPE_UINT32_T, uint32_t)

DEFINE_FIELD_SETTER(u64, TYPE_UINT64_T, uint64_t)
DEFINE_FIELD_GETTER(u64, TYPE_UINT64_T, uint64_t)

DEFINE_FIELD_SETTER(int8_t, TYPE_INT8_T, int8_t)
DEFINE_FIELD_GETTER(int8_t, TYPE_INT8_T, int8_t)

DEFINE_FIELD_SETTER(int16_t, TYPE_INT16_T, int16_t)
DEFINE_FIELD_GETTER(int16_t, TYPE_INT16_T, int16_t)

DEFINE_FIELD_SETTER(int32_t, TYPE_INT32_T, int32_t)
DEFINE_FIELD_GETTER(int32_t, TYPE_INT32_T, int32_t)

DEFINE_FIELD_SETTER(int64_t, TYPE_INT64_T, int64_t)
DEFINE_FIELD_GETTER(int64_t, TYPE_INT64_T, int64_t)

// --- Plugin-Generated-Extensions ---

// ==========================================
// Plugin: format
// ==========================================
#ifdef CMY_PLUGIN_FORMAT_ENABLED
static inline ReflectResult print_field(const void* instance, const StructFieldInfo* field)
{
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

#ifdef _MSC_VER
    size_t buflen = CMY_FORMAT_MAX_BUF_LEN;
    char buf[CMY_FORMAT_MAX_BUF_LEN];
#else // May have VLA support
    size_t buflen = field->count > 256 ? field->count : 256;
    char buf[buflen];
#endif

    ReflectResult res = get_field_as_str(instance, field, buf, buflen);
    if (res != REFLECT_OK) {
        return res;
    }

    CMY_PRINTF("%s", buf);
    return REFLECT_OK;
}

#endif // CMY_PLUGIN_FORMAT_ENABLED
#ifdef CMY_PLUGIN_FORMAT_ENABLED
static inline ReflectResult get_field_EnumType_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) {
        return REFLECT_ERR_NULL_PTR;
    }

    EnumType var;
    ReflectResult res = get_field_EnumType(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const EnumMetaData meta = EnumMetaData_FromName(EnumType);
    const char* enum_val = get_enum_member_name(meta.members, meta.count, (int)var);
    const EnumMemberInfo* info = (enum_val) ? Find_Enum_Member(meta, enum_val) : NULL;
    const EnumMemberExtension* ext = GET_MEMBER_EXT(info);

    const char* fmt = (ext && ext->display) ? ext->display : (enum_val ? enum_val : "<unknown>");
    snprintf(out_buf, buflen, "%s", fmt);
    return REFLECT_OK;
}

static inline ReflectResult get_field_str_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    char * var;
    ReflectResult res = get_field_str(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_char_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    char var;
    ReflectResult res = get_field_char(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%c";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_char_arr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) {
        return REFLECT_ERR_NULL_PTR;
    }

    #ifdef _MSC_VER
        if (field->count > CMY_FORMAT_MAX_BUF_LEN) { return REFLECT_ERR_OUT_OF_BOUNDS; }
        char var[CMY_FORMAT_MAX_BUF_LEN];;
    #else
        char var[field->count];
    #endif
    size_t arr_len = field->count;

    ReflectResult res = get_field_char_arr(instance, field, var, arr_len);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_conststr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    const char * var;
    ReflectResult res = get_field_conststr(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_int_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    int var;
    ReflectResult res = get_field_int(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%d";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_uint_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    unsigned int var;
    ReflectResult res = get_field_uint(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%u";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_short_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    short var;
    ReflectResult res = get_field_short(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%hd";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_unsignedshort_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    unsigned short var;
    ReflectResult res = get_field_unsignedshort(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%hu";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_long_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    long var;
    ReflectResult res = get_field_long(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%ld";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_unsignedlong_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    unsigned long var;
    ReflectResult res = get_field_unsignedlong(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%lu";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_unsignedchar_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    unsigned char var;
    ReflectResult res = get_field_unsignedchar(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%hhu";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_float_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    float var;
    ReflectResult res = get_field_float(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%f";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_double_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    double var;
    ReflectResult res = get_field_double(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%lf";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_u8_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    uint8_t var;
    ReflectResult res = get_field_u8(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRIu8;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_u16_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    uint16_t var;
    ReflectResult res = get_field_u16(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRIu16;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_u32_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    uint32_t var;
    ReflectResult res = get_field_u32(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRIu32;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_u64_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    uint64_t var;
    ReflectResult res = get_field_u64(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRIu64;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_int8_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    int8_t var;
    ReflectResult res = get_field_int8_t(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRId8;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_int16_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    int16_t var;
    ReflectResult res = get_field_int16_t(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRId16;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_int32_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    int32_t var;
    ReflectResult res = get_field_int32_t(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRId32;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_int64_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    int64_t var;
    ReflectResult res = get_field_int64_t(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRId64;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!field) { return REFLECT_ERR_NULL_PTR; }
    switch(field->type) {
        case TYPE_ENUM_ENUMTYPE: return get_field_EnumType_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR_PTR: return get_field_str_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR: return get_field_char_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR_ARR: return get_field_char_arr_as_str(instance, field, out_buf, buflen);
        case TYPE_CONSTCHAR_PTR: return get_field_conststr_as_str(instance, field, out_buf, buflen);
        case TYPE_INT: return get_field_int_as_str(instance, field, out_buf, buflen);
        case TYPE_UNSIGNEDINT: return get_field_uint_as_str(instance, field, out_buf, buflen);
        case TYPE_SHORT: return get_field_short_as_str(instance, field, out_buf, buflen);
        case TYPE_UNSIGNEDSHORT: return get_field_unsignedshort_as_str(instance, field, out_buf, buflen);
        case TYPE_LONG: return get_field_long_as_str(instance, field, out_buf, buflen);
        case TYPE_UNSIGNEDLONG: return get_field_unsignedlong_as_str(instance, field, out_buf, buflen);
        case TYPE_UNSIGNEDCHAR: return get_field_unsignedchar_as_str(instance, field, out_buf, buflen);
        case TYPE_FLOAT: return get_field_float_as_str(instance, field, out_buf, buflen);
        case TYPE_DOUBLE: return get_field_double_as_str(instance, field, out_buf, buflen);
        case TYPE_UINT8_T: return get_field_u8_as_str(instance, field, out_buf, buflen);
        case TYPE_UINT16_T: return get_field_u16_as_str(instance, field, out_buf, buflen);
        case TYPE_UINT32_T: return get_field_u32_as_str(instance, field, out_buf, buflen);
        case TYPE_UINT64_T: return get_field_u64_as_str(instance, field, out_buf, buflen);
        case TYPE_INT8_T: return get_field_int8_t_as_str(instance, field, out_buf, buflen);
        case TYPE_INT16_T: return get_field_int16_t_as_str(instance, field, out_buf, buflen);
        case TYPE_INT32_T: return get_field_int32_t_as_str(instance, field, out_buf, buflen);
        case TYPE_INT64_T: return get_field_int64_t_as_str(instance, field, out_buf, buflen);
        default: return REFLECT_ERR_TYPE_MISMATCH;
    }
}

#endif // CMY_PLUGIN_FORMAT_ENABLED

#endif // CMYREFLECTION_AUTOGEN_H
// --- Metadata Definitions
#ifdef REFLECTION_IMPLEMENTATION

// --- Generated from test_format_types.h ---
const StructFieldInfo StringType_Metadata[] = {
    { "char_ptr", TYPE_CHAR_PTR, offsetof(StringType, char_ptr), sizeof(char *), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "char_arr", TYPE_CHAR_ARR, offsetof(StringType, char_arr), sizeof(char[BUF_LEN]), BUF_LEN, FIELD_ACCESS_RW, NULL, NULL },
    { "constchar_ptr", TYPE_CONSTCHAR_PTR, offsetof(StringType, constchar_ptr), sizeof(const char *), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "constchar_arr", TYPE_CHAR_ARR, offsetof(StringType, constchar_arr), sizeof(char[BUF_LEN]), BUF_LEN, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t StringType_FieldCount = sizeof(StringType_Metadata) / sizeof(StructFieldInfo);

const StructFieldInfo NumTypes_Metadata[] = {
    { "i", TYPE_INT, offsetof(NumTypes, i), sizeof(int), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "ui", TYPE_UNSIGNEDINT, offsetof(NumTypes, ui), sizeof(unsigned int), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "s", TYPE_SHORT, offsetof(NumTypes, s), sizeof(short), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "us", TYPE_UNSIGNEDSHORT, offsetof(NumTypes, us), sizeof(unsigned short), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "l", TYPE_LONG, offsetof(NumTypes, l), sizeof(long), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "ul", TYPE_UNSIGNEDLONG, offsetof(NumTypes, ul), sizeof(unsigned long), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "c", TYPE_CHAR, offsetof(NumTypes, c), sizeof(char), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "uc", TYPE_UNSIGNEDCHAR, offsetof(NumTypes, uc), sizeof(unsigned char), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "f", TYPE_FLOAT, offsetof(NumTypes, f), sizeof(float), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "d", TYPE_DOUBLE, offsetof(NumTypes, d), sizeof(double), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "u8", TYPE_UINT8_T, offsetof(NumTypes, u8), sizeof(uint8_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "u16", TYPE_UINT16_T, offsetof(NumTypes, u16), sizeof(uint16_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "u32", TYPE_UINT32_T, offsetof(NumTypes, u32), sizeof(uint32_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "u64", TYPE_UINT64_T, offsetof(NumTypes, u64), sizeof(uint64_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "i8", TYPE_INT8_T, offsetof(NumTypes, i8), sizeof(int8_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "i16", TYPE_INT16_T, offsetof(NumTypes, i16), sizeof(int16_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "i32", TYPE_INT32_T, offsetof(NumTypes, i32), sizeof(int32_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "i64", TYPE_INT64_T, offsetof(NumTypes, i64), sizeof(int64_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "private", TYPE_UINT32_T, offsetof(NumTypes, private), sizeof(uint32_t), 1, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t NumTypes_FieldCount = sizeof(NumTypes_Metadata) / sizeof(StructFieldInfo);

const StructFieldInfo MockStruct_Metadata[] = {
    { "enum_type", TYPE_ENUM_ENUMTYPE, offsetof(MockStruct, enum_type), sizeof(EnumType), 1, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t MockStruct_FieldCount = sizeof(MockStruct_Metadata) / sizeof(StructFieldInfo);

const StructFieldExtension ext_Specified_as_hex = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.format = "0x%x",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};
const StructFieldExtension ext_Specified_with_prefix = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.format = "my str: %s",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};
const StructFieldExtension ext_Specified_percent = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.format = "%.2f%%",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};

const StructFieldInfo Specified_Metadata[] = {
    { "as_hex", TYPE_INT, offsetof(Specified, as_hex), sizeof(int), 1, FIELD_ACCESS_RW, NULL, (void*)&ext_Specified_as_hex },
    { "with_prefix", TYPE_CHAR_PTR, offsetof(Specified, with_prefix), sizeof(char *), 1, FIELD_ACCESS_RW, NULL, (void*)&ext_Specified_with_prefix },
    { "percent", TYPE_FLOAT, offsetof(Specified, percent), sizeof(float), 1, FIELD_ACCESS_RW, NULL, (void*)&ext_Specified_percent },
};
const size_t Specified_FieldCount = sizeof(Specified_Metadata) / sizeof(StructFieldInfo);

const EnumMemberExtension ext_EnumType_ENUM_ERR = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.display = "Error Enum",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};
const EnumMemberInfo EnumType_Members[] = {
   { ENUM_A, "ENUM_A", NULL },
   { ENUM_B, "ENUM_B", NULL },
   { ENUM_C, "ENUM_C", NULL },
   { ENUM_ERR, "ENUM_ERR", (void*)&ext_EnumType_ENUM_ERR },
};
const size_t EnumType_MemberCount = sizeof(EnumType_Members) / sizeof(EnumMemberInfo);

// --- Auto-Generated Type Registry
ReflectResult get_struct_metadata(FieldType type, StructMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_STRUCT_STRINGTYPE:
          out_meta->fields = StringType_Metadata;
          out_meta->count = StringType_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_NUMTYPES:
          out_meta->fields = NumTypes_Metadata;
          out_meta->count = NumTypes_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_MOCKSTRUCT:
          out_meta->fields = MockStruct_Metadata;
          out_meta->count = MockStruct_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_SPECIFIED:
          out_meta->fields = Specified_Metadata;
          out_meta->count = Specified_FieldCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated Type Registry
ReflectResult get_enum_metadata(FieldType type, EnumMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_ENUM_ENUMTYPE:
          out_meta->members = EnumType_Members;
          out_meta->count = EnumType_MemberCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_ENUM_INVALID;
    }
}


// --- Auto-Generated Safe Type Setter
ReflectResult safe_set_field(void* instance, const StructFieldInfo* field, const void* value, size_t element_count) {
    if (!instance || !field || !value) return false;
    switch(field->type) {
      case TYPE_STRUCT_STRINGTYPE: return set_field_StringType(instance, field, *(StringType*)value);
      case TYPE_STRUCT_NUMTYPES: return set_field_NumTypes(instance, field, *(NumTypes*)value);
      case TYPE_ENUM_ENUMTYPE: return set_field_EnumType(instance, field, *(EnumType*)value);
      case TYPE_STRUCT_MOCKSTRUCT: return set_field_MockStruct(instance, field, *(MockStruct*)value);
      case TYPE_STRUCT_SPECIFIED: return set_field_Specified(instance, field, *(Specified*)value);
      case TYPE_CHAR_PTR: return set_field_str(instance, field, *(char **)value);
      case TYPE_CHAR: return set_field_char(instance, field, *(char*)value);
      case TYPE_CHAR_ARR: return set_field_char_arr(instance, field, (char*)value, element_count);
      case TYPE_CONSTCHAR_PTR: return set_field_conststr(instance, field, *(const char **)value);
      case TYPE_CONSTCHAR: return set_field_constchar(instance, field, *(const char*)value);
      case TYPE_INT: return set_field_int(instance, field, *(int*)value);
      case TYPE_UNSIGNEDINT: return set_field_uint(instance, field, *(unsigned int*)value);
      case TYPE_SHORT: return set_field_short(instance, field, *(short*)value);
      case TYPE_UNSIGNEDSHORT: return set_field_unsignedshort(instance, field, *(unsigned short*)value);
      case TYPE_LONG: return set_field_long(instance, field, *(long*)value);
      case TYPE_UNSIGNEDLONG: return set_field_unsignedlong(instance, field, *(unsigned long*)value);
      case TYPE_UNSIGNEDCHAR: return set_field_unsignedchar(instance, field, *(unsigned char*)value);
      case TYPE_FLOAT: return set_field_float(instance, field, *(float*)value);
      case TYPE_DOUBLE: return set_field_double(instance, field, *(double*)value);
      case TYPE_UINT8_T: return set_field_u8(instance, field, *(uint8_t*)value);
      case TYPE_UINT16_T: return set_field_u16(instance, field, *(uint16_t*)value);
      case TYPE_UINT32_T: return set_field_u32(instance, field, *(uint32_t*)value);
      case TYPE_UINT64_T: return set_field_u64(instance, field, *(uint64_t*)value);
      case TYPE_INT8_T: return set_field_int8_t(instance, field, *(int8_t*)value);
      case TYPE_INT16_T: return set_field_int16_t(instance, field, *(int16_t*)value);
      case TYPE_INT32_T: return set_field_int32_t(instance, field, *(int32_t*)value);
      case TYPE_INT64_T: return set_field_int64_t(instance, field, *(int64_t*)value);
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated enum->name converter
const char* get_name_of_type(FieldType type) {
    switch(type) {
     case TYPE_CHAR: return "TYPE_CHAR";
     case TYPE_CHAR_ARR: return "TYPE_CHAR_ARR";
     case TYPE_CHAR_PTR: return "TYPE_CHAR_PTR";
     case TYPE_CONSTCHAR: return "TYPE_CONSTCHAR";
     case TYPE_CONSTCHAR_PTR: return "TYPE_CONSTCHAR_PTR";
     case TYPE_DOUBLE: return "TYPE_DOUBLE";
     case TYPE_ENUM_ENUMTYPE: return "TYPE_ENUM_ENUMTYPE";
     case TYPE_FLOAT: return "TYPE_FLOAT";
     case TYPE_INT: return "TYPE_INT";
     case TYPE_INT16_T: return "TYPE_INT16_T";
     case TYPE_INT32_T: return "TYPE_INT32_T";
     case TYPE_INT64_T: return "TYPE_INT64_T";
     case TYPE_INT8_T: return "TYPE_INT8_T";
     case TYPE_LONG: return "TYPE_LONG";
     case TYPE_SHORT: return "TYPE_SHORT";
     case TYPE_STRUCT_MOCKSTRUCT: return "TYPE_STRUCT_MOCKSTRUCT";
     case TYPE_STRUCT_NUMTYPES: return "TYPE_STRUCT_NUMTYPES";
     case TYPE_STRUCT_SPECIFIED: return "TYPE_STRUCT_SPECIFIED";
     case TYPE_STRUCT_STRINGTYPE: return "TYPE_STRUCT_STRINGTYPE";
     case TYPE_UINT16_T: return "TYPE_UINT16_T";
     case TYPE_UINT32_T: return "TYPE_UINT32_T";
     case TYPE_UINT64_T: return "TYPE_UINT64_T";
     case TYPE_UINT8_T: return "TYPE_UINT8_T";
     case TYPE_UNKNOWN: return "TYPE_UNKNOWN";
     case TYPE_UNSIGNEDCHAR: return "TYPE_UNSIGNEDCHAR";
     case TYPE_UNSIGNEDINT: return "TYPE_UNSIGNEDINT";
     case TYPE_UNSIGNEDLONG: return "TYPE_UNSIGNEDLONG";
     case TYPE_UNSIGNEDSHORT: return "TYPE_UNSIGNEDSHORT";
        default: return NULL;
    };
}

FieldType get_base_type(FieldType type) {
    switch(type) {
      case TYPE_CHAR_PTR: return TYPE_CHAR;
      case TYPE_CHAR_ARR: return TYPE_CHAR;
      case TYPE_CONSTCHAR_PTR: return TYPE_CONSTCHAR;
        default: return type;
    }
}

size_t get_type_size(FIELD_TYPE type) {
    switch(type) {
        case TYPE_STRUCT_STRINGTYPE: return sizeof(StringType);
        case TYPE_STRUCT_NUMTYPES: return sizeof(NumTypes);
        case TYPE_ENUM_ENUMTYPE: return sizeof(EnumType);
        case TYPE_STRUCT_MOCKSTRUCT: return sizeof(MockStruct);
        case TYPE_STRUCT_SPECIFIED: return sizeof(Specified);
        case TYPE_CHAR_PTR: return sizeof(char *);
        case TYPE_CHAR: return sizeof(char);
        case TYPE_CHAR_ARR: return sizeof(char *);
        case TYPE_CONSTCHAR_PTR: return sizeof(const char *);
        case TYPE_CONSTCHAR: return sizeof(const char);
        case TYPE_INT: return sizeof(int);
        case TYPE_UNSIGNEDINT: return sizeof(unsigned int);
        case TYPE_SHORT: return sizeof(short);
        case TYPE_UNSIGNEDSHORT: return sizeof(unsigned short);
        case TYPE_LONG: return sizeof(long);
        case TYPE_UNSIGNEDLONG: return sizeof(unsigned long);
        case TYPE_UNSIGNEDCHAR: return sizeof(unsigned char);
        case TYPE_FLOAT: return sizeof(float);
        case TYPE_DOUBLE: return sizeof(double);
        case TYPE_UINT8_T: return sizeof(uint8_t);
        case TYPE_UINT16_T: return sizeof(uint16_t);
        case TYPE_UINT32_T: return sizeof(uint32_t);
        case TYPE_UINT64_T: return sizeof(uint64_t);
        case TYPE_INT8_T: return sizeof(int8_t);
        case TYPE_INT16_T: return sizeof(int16_t);
        case TYPE_INT32_T: return sizeof(int32_t);
        case TYPE_INT64_T: return sizeof(int64_t);
        default: return 0;
    }
}
#endif // REFLECTION_IMPLEMENTATION
#ifdef _MSC_VER
  #pragma warning(pop)
#endif

