/*
* Auto Generated by CMyReflection python script
* Version 0.0.0
*/
// clang-format off

#define CMYREFLECTION_PARSED
#ifndef CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_REGISTRY
typedef enum {
    TYPE_CHAR,
    TYPE_CHAR_PTR,
    TYPE_ENUM_OPERATION,
    TYPE_FLOAT,
    TYPE_FLOAT_PTR,
    TYPE_SIZE_T,
    TYPE_STRUCT_EXPRESSION,
    TYPE_STRUCT_MATRIX,
    TYPE_STRUCT_STRINGVIEW,
    TYPE_STRUCT_VARIABLE,
    TYPE_UNKNOWN,
} FieldType;

#include <cmyreflection.h>

/*
 * CMyReflection Active Plugins
 *  -> Printer (v0.0.0) by oonamo - Provides run time printing for primitive types
 *    - Provides tag: @no_print (Enums) - Forces the plugin to not generate get_field_as_str for enum
 *    - Provides tag: @format(value) (Struct Fields) - Specify a C format specifier for a struct.
 *      Does not create a get_field_as_str function if not defined
 *      Example:
 *      +  typedef struct {
 *      +      // cmy:format("my type: %x")
 *      +      int x;
 *      +  } MyStruct;
 *    - Provides tag: @display(value) (Enum Members) - Specifies how an enum should be displayed.
 *      Defaults to name of the enum member if not provided
 *      Example:
 *      +  @display("enum a")
 *      +  ENUM_A
 *    - Provides macro: CMY_HAS_PRINTER_PLUGIN (Value: 1) - Printer plugin is available
 *    - Provides macro: CMY_PLUGIN_PRINTER_ENABLED (Default: 1) - Enables the Printer plugin
 *    - Provides macro: CMY_PRINTER_MAX_BUF_LEN (Default: 256) - Default buffer len for printing (_MSC_VER)
 *    - Provides macro: CMY_PRINTF (Default: printf) - Defines the printf implementation
 *    - Provides router: ReflectResult get_field_as_str(..) - Creates a get_type_as_str for the type for primitives and enums
 *      By default, enums are enabled
 *      + Types: Operation, float, size_t, char*, char
 *    - Provides function: ReflectResult print_field(...) - Prints a field, if it implements get_field_as_str
 *  -> json (v0.0.1) by oonamo - A json serializer plugin
 *    - Provides tag: @json_serialize_function(value) (Structs) - Function to call to serialize this type
 *      Example:
 *      +  @json_serialize_function(MyCoolStruct_Serializer)
 *      +  typedef struct { ... } MyCoolStruct;
 *      +  // in a seperate file
 *      +  #include "reflection.h"
 *      +  void MyCoolStruct_Serializer(const void* instance, const StructFieldInfo* field, _cmy_json_state* state);
 *    - Provides tag: @json_serialize_function(value) (Enums) - Function to call to serialize this type
 *      Example:
 *      +  @json_serialize_function(MyCoolEnum_Serializer)
 *      +  typedef enum { ... } MyCoolEnum;
 *      +  // in a seperate file
 *      +  #include "reflection.h"
 *      +  void MyCoolEnum_Serializer(const void* instance, const StructFieldInfo* field, _cmy_json_state* state);
 *    - Provides tag: @json_key_name(value) (Struct Fields) - Name of the json key
 *      Example:
 *      +  typedef struct
 *      +  {
 *      +      // cmy:json_key_name("new name")
 *      +      char* old_name;
 *      +  } MyType;
 *      Result:
 *      =  {
 *      =      "new name": "TYPE_CHAR_PTR"
 *      =  }
 *    - Provides macro: CMY_HAS_JSON_PLUGIN (Value: 1) - json plugin is available
 *    - Provides macro: CMY_PLUGIN_JSON_ENABLED (Default: 1) - Enables the json plugin
 *    - Provides macro: CMY_JSON_FMT_BUF_LEN (Default: 256) - Buffer length to use for custom format strings
 *    - Provides macro: CMY_JSON_DEBUG  - Adds debug information during certain operations
 *    - Provides macro: CMY_JSON_WRITE(state_ptr, ...) (Value: json_write_internal(state_ptr, __VA_ARGS__)) - Wrapper for json writing function
 *    - Provides router: ReflectResult json_serialize_custom(..) - Process fields dynamically based on their type
 (No types mapped)
 *    - Provides router: bool json_is_string_type(..) - Checks if a type represents a string
 *      + Types: char*
 *    - Provides router: bool json_needs_quote(..) - Dynamically determines if the type requires JSON quotes
 *      + Types: Operation, char*
 *    - Provides router: bool json_is_string_array(..) - Determines if a type is an inline array
 (No types mapped)
 *    - Provides function: void _fixed_buf_write_cb(...) - Internal fixed buffer callback wrapper
 *    - Provides function: void _json_traversal_iterator(...) - Json Traversal serializer
 *    - Provides function: void json_serialize_value(...) - Serialize a value into valid json
 *    - Provides function: void json_write_internal(...) - Internal Writing Function
 *    - Provides function: void json_write_string_escaped(...) - Safely escapes and streams strings
 *    - Provides function: ReflectResult to_json(...) - Converts a given type to a json string using a fixed buffer
 *    - Provides function: ReflectResult to_json_stream(...) - Converts a given type to a json string (streamed)
 */


// ----------------------------------------
// Generated by 'json'
// ----------------------------------------
typedef void (*cmy_json_write_cb)(const char* chunk, size_t len, void* user_ctx);

typedef struct
{
    char* _buf;
    size_t _capacity;
    size_t _current_offset;

    int indent;
    bool is_first_field;
    FIELD_TYPE current_parent_type;

    cmy_json_write_cb write_cb;
    void* cb_ctx;
} _cmy_json_state;

typedef struct
{
    char* buf;
    size_t capacity;
    size_t offset;
} _cmy_json_fixedbuf_ctx;


#define CMY_HAS_PRINTER_PLUGIN 1
#ifndef CMY_PLUGIN_PRINTER_ENABLED
#    define CMY_PLUGIN_PRINTER_ENABLED 1
#endif //CMY_PLUGIN_PRINTER_ENABLED
#ifndef CMY_PRINTER_MAX_BUF_LEN
#    define CMY_PRINTER_MAX_BUF_LEN 256
#endif //CMY_PRINTER_MAX_BUF_LEN
#ifndef CMY_PRINTF
#    define CMY_PRINTF printf
#endif //CMY_PRINTF
#define CMY_HAS_JSON_PLUGIN 1
#ifndef CMY_PLUGIN_JSON_ENABLED
#    define CMY_PLUGIN_JSON_ENABLED 1
#endif //CMY_PLUGIN_JSON_ENABLED
#ifndef CMY_JSON_FMT_BUF_LEN
#    define CMY_JSON_FMT_BUF_LEN 256
#endif //CMY_JSON_FMT_BUF_LEN
#ifndef CMY_JSON_DEBUG
    #ifdef NDEBUG
        #define CMY_JSON_DEBUG 1
    #else
        #define CMY_JSON_DEBUG 0
    #endif
#endif

#define CMY_JSON_WRITE(state_ptr, ...) json_write_internal(state_ptr, __VA_ARGS__)


// ########################################
// Printer Declarations
// ########################################
#ifdef CMY_PLUGIN_PRINTER_ENABLED
static inline ReflectResult get_field_Operation_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_char_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_float_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_size_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_str_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult print_field(const void* instance, const StructFieldInfo* field);
#endif // CMY_PLUGIN_PRINTER_ENABLED

// ########################################
// json Declarations
// ########################################
#ifdef CMY_PLUGIN_JSON_ENABLED
static void _fixed_buf_write_cb(const char* chunk, size_t len, void* user_ctx);
static inline void _json_traversal_iterator(const void            *base_instance,
                             const StructFieldInfo  *field,
                             void                   *user_data);
static inline bool json_is_string_array(FIELD_TYPE type);
static inline bool json_is_string_type(FIELD_TYPE type);
static inline bool json_needs_quote(FIELD_TYPE type);
static inline ReflectResult json_serialize_custom(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state);
static inline void json_serialize_value(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state);
static inline void json_write_internal(_cmy_json_state* state, const char* fmt, ...);
static inline void json_write_string_escaped(_cmy_json_state* state, const char* str);
static inline ReflectResult to_json(const void* instance, FIELD_TYPE root_type, char* out_buf, size_t buflen);
static inline ReflectResult to_json_stream(const void* instance, FIELD_TYPE root_type, cmy_json_write_cb write_cb, void* user_ctx);
#endif // CMY_PLUGIN_JSON_ENABLED


#include <inttypes.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
typedef struct {
#ifdef CMY_PLUGIN_PRINTER_ENABLED
     const char* format;
#endif // CMY_PLUGIN_PRINTER_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
     char* json_key_name;
#endif // CMY_PLUGIN_JSON_ENABLED
} StructFieldExtension;

typedef struct {
#ifdef CMY_PLUGIN_PRINTER_ENABLED
     const char* display;
#endif // CMY_PLUGIN_PRINTER_ENABLED
} EnumMemberExtension;
// --- Metadata Declarations
extern const StructFieldInfo Matrix_Metadata[];
extern const size_t Matrix_FieldCount;
extern const StructFieldInfo StringView_Metadata[];
extern const size_t StringView_FieldCount;
extern const StructFieldInfo Variable_Metadata[];
extern const size_t Variable_FieldCount;
extern const StructFieldInfo Expression_Metadata[];
extern const size_t Expression_FieldCount;
extern const EnumMemberInfo Operation_Members[];
extern const size_t Operation_MemberCount;
extern const EnumMemberExtension ext_Operation_MUL;
extern const EnumMemberExtension ext_Operation_INVERSE;
extern const EnumMemberExtension ext_Operation_TRANSPOSE;
extern const EnumMemberExtension ext_Operation_DET;

#define GET_FIELD_EXT(field_ptr) \
    ((field_ptr) && (field_ptr)->user_data ? (const StructFieldExtension*)((field_ptr)->user_data) : NULL)

#define GET_MEMBER_EXT(member_ptr) \
    ((member_ptr) && (member_ptr)->user_data ? ((const EnumMemberExtension*)(member_ptr->user_data)) : NULL)

// --- Auto-Generated Enum Validators ---

static inline bool is_valid_Operation(Operation value) {
    switch(value) {
      case MUL:
      case INVERSE:
      case TRANSPOSE:
      case DET:
           return true;
    default:
        return false;
    }
}

DEFINE_ENUM_SETTER(Operation, TYPE_ENUM_OPERATION, Operation, is_valid_Operation)
DEFINE_FIELD_GETTER(Operation, TYPE_ENUM_OPERATION, Operation)

DEFINE_FIELD_SETTER(Matrix, TYPE_STRUCT_MATRIX, Matrix)
DEFINE_FIELD_GETTER(Matrix, TYPE_STRUCT_MATRIX, Matrix)

DEFINE_FIELD_SETTER(StringView, TYPE_STRUCT_STRINGVIEW, StringView)
DEFINE_FIELD_GETTER(StringView, TYPE_STRUCT_STRINGVIEW, StringView)

DEFINE_FIELD_SETTER(Variable, TYPE_STRUCT_VARIABLE, Variable)
DEFINE_FIELD_GETTER(Variable, TYPE_STRUCT_VARIABLE, Variable)

DEFINE_FIELD_SETTER(Expression, TYPE_STRUCT_EXPRESSION, Expression)
DEFINE_FIELD_GETTER(Expression, TYPE_STRUCT_EXPRESSION, Expression)

DEFINE_FIELD_SETTER(float_ptr, TYPE_FLOAT_PTR, float *)
DEFINE_FIELD_GETTER(float_ptr, TYPE_FLOAT_PTR, float *)

DEFINE_FIELD_SETTER(float, TYPE_FLOAT, float)
DEFINE_FIELD_GETTER(float, TYPE_FLOAT, float)

DEFINE_FIELD_SETTER(size_t, TYPE_SIZE_T, size_t)
DEFINE_FIELD_GETTER(size_t, TYPE_SIZE_T, size_t)

DEFINE_FIELD_SETTER(str, TYPE_CHAR_PTR, char  *)
DEFINE_FIELD_GETTER(str, TYPE_CHAR_PTR, char  *)

DEFINE_FIELD_SETTER(char, TYPE_CHAR, char)
DEFINE_FIELD_GETTER(char, TYPE_CHAR, char)

// --- Plugin-Generated-Extensions ---

// ==========================================
// Plugin: Printer
// ==========================================
#ifdef CMY_PLUGIN_PRINTER_ENABLED
static inline ReflectResult print_field(const void* instance, const StructFieldInfo* field)
{
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

#ifdef _MSC_VER
    size_t buflen = CMY_PRINTER_MAX_BUF_LEN;
    char buf[CMY_PRINTER_MAX_BUF_LEN];
#else // May have VLA support
    size_t buflen = field->count > 256 ? field->count : 256;
    char buf[buflen];
#endif

    ReflectResult res = get_field_as_str(instance, field, buf, buflen);
    if (res != REFLECT_OK) {
        return res;
    }

    CMY_PRINTF("%s", buf);
    return REFLECT_OK;
}

#endif // CMY_PLUGIN_PRINTER_ENABLED
#ifdef CMY_PLUGIN_PRINTER_ENABLED
static inline ReflectResult get_field_Operation_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) {
        return REFLECT_ERR_NULL_PTR;
    }

    Operation var;
    ReflectResult res = get_field_Operation(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const EnumMetaData meta = EnumMetaData_FromName(Operation);
    const char* enum_val = get_enum_member_name(meta.members, meta.count, var);
    const EnumMemberInfo* info = (enum_val) ? Find_Enum_Member(meta, enum_val) : NULL;
    const EnumMemberExtension* ext = GET_MEMBER_EXT(info);

    const char* fmt = (ext && ext->display) ? ext->display : (enum_val ? enum_val : "<unknown>");
    snprintf(out_buf, buflen, "%s", fmt);
    return REFLECT_OK;
}

static inline ReflectResult get_field_float_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    float var;
    ReflectResult res = get_field_float(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%f";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_size_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    size_t var;
    ReflectResult res = get_field_size_t(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%zu";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_str_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    char  * var;
    ReflectResult res = get_field_str(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_char_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    char var;
    ReflectResult res = get_field_char(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%c";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!field) { return REFLECT_ERR_NULL_PTR; }
    switch(field->type) {
        case TYPE_ENUM_OPERATION: return get_field_Operation_as_str(instance, field, out_buf, buflen);
        case TYPE_FLOAT: return get_field_float_as_str(instance, field, out_buf, buflen);
        case TYPE_SIZE_T: return get_field_size_t_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR_PTR: return get_field_str_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR: return get_field_char_as_str(instance, field, out_buf, buflen);
        default: return REFLECT_ERR_TYPE_MISMATCH;
    }
}

#endif // CMY_PLUGIN_PRINTER_ENABLED

// ==========================================
// Plugin: json
// ==========================================
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void json_serialize_value(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state)
{
    if (json_serialize_custom(exact_data_ptr, actual_type, field_ctx, state) == REFLECT_OK)
    {
        return;
    }

    StructMetaData meta;
    if (get_struct_metadata(actual_type, &meta) == REFLECT_OK) {
        CMY_JSON_WRITE(state, "{\n");

        _cmy_json_state nested_state = *state;
        nested_state.indent += 4;
        nested_state.is_first_field = true;
        nested_state.current_parent_type = actual_type;

        visit_struct_fields(exact_data_ptr, actual_type, _json_traversal_iterator, &nested_state);

        state->_current_offset = nested_state._current_offset;
        CMY_JSON_WRITE(state, "\n%*s}", state->indent, "");
        return;
    }

    if (exact_data_ptr && json_is_string_type(actual_type)) {
        const StructFieldExtension* ext = GET_FIELD_EXT(field_ctx);
        const char* fmt = (ext && ext->format) ? ext->format : "%s";

        StructFieldInfo element_field = {0};
        if (field_ctx) {
            element_field = *field_ctx;
            element_field.offset = 0;

            if (!json_is_string_array(actual_type)) {
                element_field.count = 0;
            }
        }

        // Default
        if (strcmp(fmt, "%s") == 0) {
            const char* str_ptr = NULL;

            // exact_data_ptr is ptr to static array
            if (json_is_string_array(actual_type)) {
                str_ptr = (const char*)exact_data_ptr;
            } else {
                get_field_value(exact_data_ptr, &element_field, (void*)&str_ptr, sizeof(const char*));
            }

            json_write_string_escaped(state, str_ptr);
        } else {
            char fmt_buf[CMY_JSON_FMT_BUF_LEN];
            if (field_ctx) {
                get_field_as_str(exact_data_ptr, &element_field, fmt_buf, sizeof(fmt_buf));
            }
            json_write_string_escaped(state, fmt_buf);
        }
        return;
    }

    char val_buf[256] = "null";
    bool force_quotes = false;
    bool is_explicit_null = false;

    if (exact_data_ptr) {
        StructFieldInfo element_field = *field_ctx;
        element_field.type = actual_type;
        element_field.offset = 0;

        if (!json_is_string_type(actual_type)) {
            element_field.count = 1;
        }

        if (get_field_as_str(exact_data_ptr, &element_field, val_buf, sizeof(val_buf)) != REFLECT_OK) {
#if CMY_JSON_DEBUG
            snprintf(val_buf, sizeof(val_buf), "<unsupported: %s at %p>", get_name_of_type(actual_type), exact_data_ptr);
#else
            snprintf(val_buf, sizeof(val_buf), "<unsupported: %s>", get_name_of_type(actual_type));
#endif
            force_quotes = true;
        }
        else if (strcmp(val_buf, "(null)") == 0) {
            snprintf(val_buf, sizeof(val_buf), "null");
            is_explicit_null = true;
        }
    } else {
        snprintf(val_buf, sizeof(val_buf), "%s", get_name_of_type(actual_type));
    }

    if (force_quotes || !exact_data_ptr || (json_needs_quote(actual_type) && !is_explicit_null)) {
        CMY_JSON_WRITE(state, "\"%s\"", val_buf);
    } else {
        CMY_JSON_WRITE(state, "%s", val_buf);
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void json_write_internal(_cmy_json_state* state, const char* fmt, ...)
{
    char scratch[128];

    va_list args;
    va_start(args, fmt);
    int written = vsnprintf(scratch, sizeof(scratch), fmt, args);
    va_end(args);

    if (written < 0) { return; }

    size_t len_to_write = ((size_t)written < sizeof(scratch)) ? (size_t)written : sizeof(scratch) - 1;

    state->write_cb(scratch, len_to_write, state->cb_ctx);
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void _json_traversal_iterator(const void            *base_instance,
                             const StructFieldInfo  *field,
                             void                   *user_data)
{
    if (!field || !(field->flags & FIELD_ACCESS_READ)) { return; }

    _cmy_json_state *state = (_cmy_json_state*)user_data;
    if (!state->is_first_field) {
        CMY_JSON_WRITE(state, ",\n");
    } else {
        state->is_first_field = false;
    }

    // Print Key
    const StructFieldExtension* ext = GET_FIELD_EXT(field);
    const char* key = (ext && ext->json_key_name) ? ext->json_key_name : field->name;
    CMY_JSON_WRITE(state, "%*s\"%s\": ", state->indent, "", key);

    bool is_string = json_is_string_type(field->type);
    bool is_dynamic = field->length_field_name != NULL;
    bool is_arr = (is_dynamic || (field->count > 1)) && !is_string;

    if (is_arr) {
        if (!base_instance) {
            const char* type_name = get_name_of_type(get_base_type(field->type));
            if (is_dynamic) {
                CMY_JSON_WRITE(state, "[\"%s (dynamic: %s)\"]", type_name, field->length_field_name);
            } else if (is_arr) {
                CMY_JSON_WRITE(state, "[\"%s (max: %zu)\"]", type_name, field->count);
            }
            return;
        }

        size_t array_len = 0;
        const void* array_ptr = NULL;
        FIELD_TYPE base_type = get_base_type(field->type);
        size_t base_size = get_type_size(base_type);

        if (is_dynamic) {
            if (get_dynamic_array_length(base_instance, state->current_parent_type, field, &array_len) != REFLECT_OK) {
                CMY_JSON_WRITE(state, "null");
                return;
            }
            if (get_field_value(base_instance, field, (void*)&array_ptr, sizeof(void*)) != REFLECT_OK)
            {
                CMY_JSON_WRITE(state, "null");
                return;
            }
        } else {
            array_len = field->count;
            array_ptr = (const char*)base_instance + field->offset;
        }

        CMY_JSON_WRITE(state, "[\n");
        _cmy_json_state arr_state = *state;
        arr_state.indent += 4;

        for (size_t i = 0; i < array_len; i++)
        {
            CMY_JSON_WRITE(&arr_state, "%*s", arr_state.indent, "");
            void* ith_element = (char*)array_ptr + (i * base_size);

            if (!ith_element) {
                CMY_JSON_WRITE(&arr_state, "null");
            } else {
                json_serialize_value(ith_element, base_type, field, &arr_state);
            }

            if (i < array_len - 1) {
                CMY_JSON_WRITE(&arr_state, ",\n");
            } else {
                CMY_JSON_WRITE(&arr_state, "\n");
            }
        }
        state->_current_offset = arr_state._current_offset;
        CMY_JSON_WRITE(state, "%*s]", state->indent, "");

        return;
    } else {
        const void* data_ptr = base_instance ? ((const char*)base_instance + field->offset) : NULL;
        json_serialize_value(data_ptr, field->type, field, state);
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static void _fixed_buf_write_cb(const char* chunk, size_t len, void* user_ctx)
{
    _cmy_json_fixedbuf_ctx* mem = (_cmy_json_fixedbuf_ctx*)user_ctx;

    size_t available = mem->capacity - mem->offset - 1;
    if (available == 0) return;

    size_t to_write = (len < available) ? len : available;

    memcpy(mem->buf + mem->offset, chunk, to_write);
    mem->offset += to_write;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void json_write_string_escaped(_cmy_json_state* state, const char* str)
{
    if (!str) {
        state->write_cb("null", 4, state->cb_ctx);
        return;
    }

    state->write_cb("\"", 1, state->cb_ctx);

    const char* p = str;
    while (*p) {
        switch(*p) {
            case '"':  state->write_cb("\\\"", 2, state->cb_ctx); break;
            case '\\': state->write_cb("\\\\", 2, state->cb_ctx); break;
            case '\b': state->write_cb("\\b",  2, state->cb_ctx); break;
            case '\f': state->write_cb("\\f",  2, state->cb_ctx); break;
            case '\n': state->write_cb("\\n",  2, state->cb_ctx); break;
            case '\r': state->write_cb("\\r",  2, state->cb_ctx); break;
            case '\t': state->write_cb("\\t", 2, state->cb_ctx); break;
            default:   state->write_cb(p, 1, state->cb_ctx); break;
        }
        p++;
    }

    state->write_cb("\"", 1, state->cb_ctx);
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline ReflectResult to_json_stream(const void* instance, FIELD_TYPE root_type, cmy_json_write_cb write_cb, void* user_ctx)
{
    if (!write_cb) { return REFLECT_ERR_NULL_PTR; }

    _cmy_json_state state = {
        .indent = 0,
        .is_first_field = true,
        .current_parent_type = root_type,
        .write_cb = write_cb,
        .cb_ctx = user_ctx,
    };

    json_serialize_value(instance, root_type, NULL, &state);

    return REFLECT_OK;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline ReflectResult to_json(const void* instance, FIELD_TYPE root_type, char* out_buf, size_t buflen)
{
    if (!out_buf || buflen == 0) { return REFLECT_ERR_NULL_PTR; }

    _cmy_json_fixedbuf_ctx ctx = {
        .buf = out_buf,
        .capacity = buflen,
        .offset = 0
    };

    ReflectResult res = to_json_stream(instance, root_type, _fixed_buf_write_cb, &ctx);

    ctx.buf[ctx.offset] = '\0';

    return res;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline ReflectResult json_serialize_custom(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state) {
    
    return REFLECT_ERR_TYPE_MISMATCH;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline bool json_is_string_type(FIELD_TYPE type) {
    
    switch(type) {
        case TYPE_CHAR_PTR: return true;
        default: return false;
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline bool json_needs_quote(FIELD_TYPE type) {
    
    switch(type) {
        case TYPE_ENUM_OPERATION: return true;
        case TYPE_CHAR_PTR: return true;
        default: return false;
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline bool json_is_string_array(FIELD_TYPE type) {
    
    return false;
}

#endif // CMY_PLUGIN_JSON_ENABLED

#endif // CMYREFLECTION_AUTOGEN_H
// --- Metadata Definitions
#ifdef REFLECTION_IMPLEMENTATION

// --- Generated from types.h ---
const StructFieldInfo Matrix_Metadata[] = {
    { "data", TYPE_FLOAT_PTR, offsetof(Matrix, data), sizeof(float *), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "cols", TYPE_SIZE_T, offsetof(Matrix, cols), sizeof(size_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "rows", TYPE_SIZE_T, offsetof(Matrix, rows), sizeof(size_t), 1, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t Matrix_FieldCount = sizeof(Matrix_Metadata) / sizeof(StructFieldInfo);

const StructFieldInfo StringView_Metadata[] = {
    { "buf", TYPE_CHAR_PTR, offsetof(StringView, buf), sizeof(char  *), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "buflen", TYPE_SIZE_T, offsetof(StringView, buflen), sizeof(size_t), 1, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t StringView_FieldCount = sizeof(StringView_Metadata) / sizeof(StructFieldInfo);

const StructFieldInfo Variable_Metadata[] = {
    { "shortname", TYPE_CHAR, offsetof(Variable, shortname), sizeof(char), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "name", TYPE_STRUCT_STRINGVIEW, offsetof(Variable, name), sizeof(StringView), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "matrix", TYPE_STRUCT_MATRIX, offsetof(Variable, matrix), sizeof(Matrix), 1, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t Variable_FieldCount = sizeof(Variable_Metadata) / sizeof(StructFieldInfo);

const StructFieldInfo Expression_Metadata[] = {
    { "lhs", TYPE_STRUCT_VARIABLE, offsetof(Expression, lhs), sizeof(Variable), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "rhs", TYPE_STRUCT_VARIABLE, offsetof(Expression, rhs), sizeof(Variable), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "op", TYPE_ENUM_OPERATION, offsetof(Expression, op), sizeof(Operation), 1, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t Expression_FieldCount = sizeof(Expression_Metadata) / sizeof(StructFieldInfo);

const EnumMemberExtension ext_Operation_MUL = {
#ifdef CMY_PLUGIN_PRINTER_ENABLED
.display = "*",
#endif // CMY_PLUGIN_PRINTER_ENABLED
};
const EnumMemberExtension ext_Operation_INVERSE = {
#ifdef CMY_PLUGIN_PRINTER_ENABLED
.display = "^-1",
#endif // CMY_PLUGIN_PRINTER_ENABLED
};
const EnumMemberExtension ext_Operation_TRANSPOSE = {
#ifdef CMY_PLUGIN_PRINTER_ENABLED
.display = "^T",
#endif // CMY_PLUGIN_PRINTER_ENABLED
};
const EnumMemberExtension ext_Operation_DET = {
#ifdef CMY_PLUGIN_PRINTER_ENABLED
.display = "det",
#endif // CMY_PLUGIN_PRINTER_ENABLED
};
const EnumMemberInfo Operation_Members[] = {
   { MUL, "MUL", (void*)&ext_Operation_MUL },
   { INVERSE, "INVERSE", (void*)&ext_Operation_INVERSE },
   { TRANSPOSE, "TRANSPOSE", (void*)&ext_Operation_TRANSPOSE },
   { DET, "DET", (void*)&ext_Operation_DET },
};
const size_t Operation_MemberCount = sizeof(Operation_Members) / sizeof(EnumMemberInfo);

// --- Auto-Generated Type Registry
ReflectResult get_struct_metadata(FieldType type, StructMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_STRUCT_MATRIX:
          out_meta->fields = Matrix_Metadata;
          out_meta->count = Matrix_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_STRINGVIEW:
          out_meta->fields = StringView_Metadata;
          out_meta->count = StringView_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_VARIABLE:
          out_meta->fields = Variable_Metadata;
          out_meta->count = Variable_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_EXPRESSION:
          out_meta->fields = Expression_Metadata;
          out_meta->count = Expression_FieldCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated Type Registry
ReflectResult get_enum_metadata(FieldType type, EnumMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_ENUM_OPERATION:
          out_meta->members = Operation_Members;
          out_meta->count = Operation_MemberCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_ENUM_INVALID;
    }
}


// --- Auto-Generated Safe Type Setter
ReflectResult safe_set_field(void* instance, const StructFieldInfo* field, const void* value, size_t element_count) {
    if (!instance || !field || !value) return false;
    switch(field->type) {
      case TYPE_ENUM_OPERATION: return set_field_Operation(instance, field, *(Operation*)value);
      case TYPE_STRUCT_MATRIX: return set_field_Matrix(instance, field, *(Matrix*)value);
      case TYPE_STRUCT_STRINGVIEW: return set_field_StringView(instance, field, *(StringView*)value);
      case TYPE_STRUCT_VARIABLE: return set_field_Variable(instance, field, *(Variable*)value);
      case TYPE_STRUCT_EXPRESSION: return set_field_Expression(instance, field, *(Expression*)value);
      case TYPE_FLOAT_PTR: return set_field_float_ptr(instance, field, *(float **)value);
      case TYPE_FLOAT: return set_field_float(instance, field, *(float*)value);
      case TYPE_SIZE_T: return set_field_size_t(instance, field, *(size_t*)value);
      case TYPE_CHAR_PTR: return set_field_str(instance, field, *(char  **)value);
      case TYPE_CHAR: return set_field_char(instance, field, *(char*)value);
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated enum->name converter
const char* get_name_of_type(FieldType type) {
    switch(type) {
     case TYPE_CHAR: return "TYPE_CHAR";
     case TYPE_CHAR_PTR: return "TYPE_CHAR_PTR";
     case TYPE_ENUM_OPERATION: return "TYPE_ENUM_OPERATION";
     case TYPE_FLOAT: return "TYPE_FLOAT";
     case TYPE_FLOAT_PTR: return "TYPE_FLOAT_PTR";
     case TYPE_SIZE_T: return "TYPE_SIZE_T";
     case TYPE_STRUCT_EXPRESSION: return "TYPE_STRUCT_EXPRESSION";
     case TYPE_STRUCT_MATRIX: return "TYPE_STRUCT_MATRIX";
     case TYPE_STRUCT_STRINGVIEW: return "TYPE_STRUCT_STRINGVIEW";
     case TYPE_STRUCT_VARIABLE: return "TYPE_STRUCT_VARIABLE";
     case TYPE_UNKNOWN: return "TYPE_UNKNOWN";
        default: return NULL;
    };
}

FieldType get_base_type(FieldType type) {
    switch(type) {
      case TYPE_FLOAT_PTR: return TYPE_FLOAT;
      case TYPE_CHAR_PTR: return TYPE_CHAR;
        default: return type;
    }
}

size_t get_type_size(FIELD_TYPE type) {
    switch(type) {
        case TYPE_ENUM_OPERATION: return sizeof(Operation);
        case TYPE_STRUCT_MATRIX: return sizeof(Matrix);
        case TYPE_STRUCT_STRINGVIEW: return sizeof(StringView);
        case TYPE_STRUCT_VARIABLE: return sizeof(Variable);
        case TYPE_STRUCT_EXPRESSION: return sizeof(Expression);
        case TYPE_FLOAT_PTR: return sizeof(float *);
        case TYPE_FLOAT: return sizeof(float);
        case TYPE_SIZE_T: return sizeof(size_t);
        case TYPE_CHAR_PTR: return sizeof(char  *);
        case TYPE_CHAR: return sizeof(char);
        default: return 0;
    }
}
#endif // REFLECTION_IMPLEMENTATION

