
/*
* Auto Generated by CMyReflection python script
* Version 0.0.0
*/
// clang-format off

#define CMYREFLECTION_PARSED
#ifndef _CMYREFLECTION_AUTOGEN
#define _CMYREFLECTION_AUTOGEN
typedef enum {
    TYPE_CHAR,
    TYPE_DAMAGE_COMPONENT,
    TYPE_FLOAT,
    TYPE_INT,
    TYPE_STR,
    TYPE_UNKNOWN,
    TYPE_VEC2,
} FieldType;

#include <cmyreflection.h>
// --- Metadata Declarations
extern const FieldInfo Vector2_Metadata[];
extern const size_t Vector2_FieldCount;
extern const FieldInfo Game_Metadata[];
extern const size_t Game_FieldCount;
extern const FieldInfo DamageComponent_Metadata[];
extern const size_t DamageComponent_FieldCount;

DEFINE_FIELD_SETTER(int, TYPE_INT, int)
DEFINE_FIELD_SETTER(float, TYPE_FLOAT, float)
DEFINE_FIELD_SETTER(char, TYPE_CHAR, char)
DEFINE_FIELD_SETTER(str, TYPE_STR, char*)
DEFINE_FIELD_SETTER(conststr, TYPE_STR, constchar*)
DEFINE_FIELD_SETTER(Vector2, TYPE_VEC2, Vector2)
DEFINE_FIELD_SETTER(DamageComponent, TYPE_DAMAGE_COMPONENT, DamageComponent)

#endif // _CMYREFLECTION_AUTOGEN
// --- Metadata Definitions
#ifdef REFLECTION_IMPLEMENTATION

// --- Generated from .\test\mocks\game_type.c ---
const FieldInfo Vector2_Metadata[] = {
    { "x", TYPE_FLOAT, offsetof(Vector2, x), sizeof(float) },
    { "y", TYPE_FLOAT, offsetof(Vector2, y), sizeof(float) },
};
const size_t Vector2_FieldCount = sizeof(Vector2_Metadata) / sizeof(FieldInfo);

const FieldInfo Game_Metadata[] = {
    { "player_pos", TYPE_VEC2, offsetof(Game, player_pos), sizeof(Vector2) },
    { "health", TYPE_FLOAT, offsetof(Game, health), sizeof(float) },
    { "level", TYPE_INT, offsetof(Game, level), sizeof(int) },
    { "player_name", TYPE_STR, offsetof(Game, player_name), sizeof(char *) },
    { "damage", TYPE_DAMAGE_COMPONENT, offsetof(Game, damage), sizeof(DamageComponent) },
};
const size_t Game_FieldCount = sizeof(Game_Metadata) / sizeof(FieldInfo);

// --- Generated from .\test\mocks\stuff.h ---
const FieldInfo DamageComponent_Metadata[] = {
    { "damage", TYPE_FLOAT, offsetof(DamageComponent, damage), sizeof(float) },
};
const size_t DamageComponent_FieldCount = sizeof(DamageComponent_Metadata) / sizeof(FieldInfo);

#endif // REFLECTION_IMPLEMENTATION
