/*
* Auto Generated by CMyReflection python script
* Version 0.0.0
*/
// clang-format off

#define CMYREFLECTION_PARSED
#ifndef CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_REGISTRY
typedef enum {
    TYPE_CHAR_ARR,
    TYPE_CONSTSTR,
    TYPE_ENUM_ACCOUNTSTATE,
    TYPE_ENUM_PERMISSIONS,
    TYPE_POST_PTR,
    TYPE_STR,
    TYPE_STRUCTPOST_PTR,
    TYPE_STRUCT_POST,
    TYPE_STRUCT_USER,
    TYPE_UINT32_T,
    TYPE_UINT64_T,
    TYPE_UNKNOWN,
} FieldType;

#include <cmyreflection.h>
// --- Metadata Declarations
extern const FieldInfo Post_Metadata[];
extern const size_t Post_FieldCount;
extern const FieldInfo User_Metadata[];
extern const size_t User_FieldCount;
extern const EnumMemberInfo Permissions_Members[];
extern const size_t Permissions_MemberCount;
extern const EnumMemberInfo AccountState_Members[];
extern const size_t AccountState_MemberCount;

// --- Auto-Generated Enum Validators ---

// Permissions is unchecked

static inline bool is_valid_AccountState(AccountState value) {
    switch(value) {
      case ACCOUNT_ACTIVE:
      case ACCOUNT_INACTIVE:
      case ACCOUNT_STALE:
           return true;
    default:
        return false;
    }
}

DEFINE_FIELD_SETTER(str, TYPE_STR, char *)
DEFINE_FIELD_GETTER(str, TYPE_STR, char *)

DEFINE_FIELD_SETTER(conststr, TYPE_CONSTSTR, const char *)
DEFINE_FIELD_GETTER(conststr, TYPE_CONSTSTR, const char *)

DEFINE_FIELD_SETTER(Permissions, TYPE_ENUM_PERMISSIONS, Permissions)
DEFINE_FIELD_GETTER(Permissions, TYPE_ENUM_PERMISSIONS, Permissions)

DEFINE_ENUM_SETTER(AccountState, TYPE_ENUM_ACCOUNTSTATE, AccountState, is_valid_AccountState)
DEFINE_FIELD_GETTER(AccountState, TYPE_ENUM_ACCOUNTSTATE, AccountState)

DEFINE_FIELD_SETTER(Post, TYPE_STRUCT_POST, Post)
DEFINE_FIELD_GETTER(Post, TYPE_STRUCT_POST, Post)

DEFINE_FIELD_SETTER(User, TYPE_STRUCT_USER, User)
DEFINE_FIELD_GETTER(User, TYPE_STRUCT_USER, User)

DEFINE_ARRAY_SETTER(char_arr, TYPE_CHAR_ARR, char *, char)
DEFINE_ARRAY_GETTER(char_arr, TYPE_CHAR_ARR, char *, char)

DEFINE_FIELD_SETTER(u32, TYPE_UINT32_T, uint32_t)
DEFINE_FIELD_GETTER(u32, TYPE_UINT32_T, uint32_t)

DEFINE_FIELD_SETTER(structPost_ptr, TYPE_STRUCTPOST_PTR, struct Post *)
DEFINE_FIELD_GETTER(structPost_ptr, TYPE_STRUCTPOST_PTR, struct Post *)

DEFINE_FIELD_SETTER(uint64_t, TYPE_UINT64_T, uint64_t)
DEFINE_FIELD_GETTER(uint64_t, TYPE_UINT64_T, uint64_t)

DEFINE_FIELD_SETTER(Post_ptr, TYPE_POST_PTR, Post *)
DEFINE_FIELD_GETTER(Post_ptr, TYPE_POST_PTR, Post *)


#endif // CMYREFLECTION_AUTOGEN_H
// --- Metadata Definitions
#ifdef REFLECTION_IMPLEMENTATION

// --- Generated from types.h ---
const FieldInfo Post_Metadata[] = {
    { "title", TYPE_CHAR_ARR, offsetof(Post, title), sizeof(char[MAX_TITLE_LEN]), MAX_TITLE_LEN, FIELD_ACCESS_RW, NULL },
    { "likes", TYPE_UINT32_T, offsetof(Post, likes), sizeof(uint32_t), 1, FIELD_ACCESS_RW, NULL },
    { "references", TYPE_STRUCTPOST_PTR, offsetof(Post, references), sizeof(struct Post *), 1, FIELD_ACCESS_RW, NULL },
};
const size_t Post_FieldCount = sizeof(Post_Metadata) / sizeof(FieldInfo);

const FieldInfo User_Metadata[] = {
    { "username", TYPE_CHAR_ARR, offsetof(User, username), sizeof(char[32]), 32, FIELD_ACCESS_RW, NULL },
    { "email", TYPE_CHAR_ARR, offsetof(User, email), sizeof(char[64]), 64, FIELD_ACCESS_RW, NULL },
    { "account_id", TYPE_UINT64_T, offsetof(User, account_id), sizeof(uint64_t), 1, FIELD_ACCESS_READ, NULL },
    { "password_hash", TYPE_CHAR_ARR, offsetof(User, password_hash), sizeof(char[64]), 64, FIELD_ACCESS_WRITE, NULL },
    { "permissions", TYPE_ENUM_PERMISSIONS, offsetof(User, permissions), sizeof(Permissions), 1, FIELD_ACCESS_RW, NULL },
    { "state", TYPE_ENUM_ACCOUNTSTATE, offsetof(User, state), sizeof(AccountState), 1, FIELD_ACCESS_RW, NULL },
    { "posts", TYPE_POST_PTR, offsetof(User, posts), sizeof(Post *), 1, FIELD_ACCESS_RW, NULL },
};
const size_t User_FieldCount = sizeof(User_Metadata) / sizeof(FieldInfo);

const EnumMemberInfo Permissions_Members[] = {
   { PERM_CREATE, "PERM_CREATE" },
   { PERM_DELETE, "PERM_DELETE" },
   { PERM_UPDATE, "PERM_UPDATE" },
};
const size_t Permissions_MemberCount = sizeof(Permissions_Members) / sizeof(EnumMemberInfo);

const EnumMemberInfo AccountState_Members[] = {
   { ACCOUNT_ACTIVE, "ACCOUNT_ACTIVE" },
   { ACCOUNT_INACTIVE, "ACCOUNT_INACTIVE" },
   { ACCOUNT_STALE, "ACCOUNT_STALE" },
};
const size_t AccountState_MemberCount = sizeof(AccountState_Members) / sizeof(EnumMemberInfo);

// --- Auto-Generated Type Registry
ReflectResult get_struct_metadata(FieldType type, StructMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_STRUCT_POST:
          out_meta->fields = Post_Metadata;
          out_meta->count = Post_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_USER:
          out_meta->fields = User_Metadata;
          out_meta->count = User_FieldCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated Type Registry
ReflectResult get_enum_metadata(FieldType type, EnumMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_ENUM_PERMISSIONS:
          out_meta->members = Permissions_Members;
          out_meta->count = Permissions_MemberCount;
          return REFLECT_OK;
      case TYPE_ENUM_ACCOUNTSTATE:
          out_meta->members = AccountState_Members;
          out_meta->count = AccountState_MemberCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_ENUM_INVALID;
    }
}


// --- Auto-Generated Safe Type Setter
ReflectResult safe_set_field(void* instance, const FieldInfo* field, const void* value, size_t element_count) {
    if (!instance || !field || !value) return false;
    switch(field->type) {
      case TYPE_STR: return set_field_str(instance, field, *(char **)value);
      case TYPE_CONSTSTR: return set_field_conststr(instance, field, *(const char **)value);
      case TYPE_ENUM_PERMISSIONS: return set_field_Permissions(instance, field, *(Permissions*)value);
      case TYPE_ENUM_ACCOUNTSTATE: return set_field_AccountState(instance, field, *(AccountState*)value);
      case TYPE_STRUCT_POST: return set_field_Post(instance, field, *(Post*)value);
      case TYPE_STRUCT_USER: return set_field_User(instance, field, *(User*)value);
      case TYPE_CHAR_ARR: return set_field_char_arr(instance, field, (char*)value, element_count);
      case TYPE_UINT32_T: return set_field_u32(instance, field, *(uint32_t*)value);
      case TYPE_STRUCTPOST_PTR: return set_field_structPost_ptr(instance, field, *(struct Post **)value);
      case TYPE_UINT64_T: return set_field_uint64_t(instance, field, *(uint64_t*)value);
      case TYPE_POST_PTR: return set_field_Post_ptr(instance, field, *(Post **)value);
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated enum->name converter
const char* get_name_of_type(FieldType type) {
    switch(type) {
     case TYPE_CHAR_ARR: return "TYPE_CHAR_ARR";
     case TYPE_CONSTSTR: return "TYPE_CONSTSTR";
     case TYPE_ENUM_ACCOUNTSTATE: return "TYPE_ENUM_ACCOUNTSTATE";
     case TYPE_ENUM_PERMISSIONS: return "TYPE_ENUM_PERMISSIONS";
     case TYPE_POST_PTR: return "TYPE_POST_PTR";
     case TYPE_STR: return "TYPE_STR";
     case TYPE_STRUCTPOST_PTR: return "TYPE_STRUCTPOST_PTR";
     case TYPE_STRUCT_POST: return "TYPE_STRUCT_POST";
     case TYPE_STRUCT_USER: return "TYPE_STRUCT_USER";
     case TYPE_UINT32_T: return "TYPE_UINT32_T";
     case TYPE_UINT64_T: return "TYPE_UINT64_T";
     case TYPE_UNKNOWN: return "TYPE_UNKNOWN";
        default: return NULL;
    };
}

#endif // REFLECTION_IMPLEMENTATION

