/*
* Auto Generated by CMyReflection python script
* Version 1.0.1
*
* USAGE:
* In EXACTLY ONE .c file, set up the implementations
*   #include "your_types.h"
*   #define CMYREFLECTION_IMPLEMENTATION
*   #define REFLECTION_IMPLEMENTATION
*   #define "this_generated_file.h"
*/

#ifdef _MSC_VER
   #pragma warning(push)
   #pragma warning(disable : 4996)
#endif
#define CMYREFLECTION_PARSED
#ifndef CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_AUTOGEN_H
#define CMYREFLECTION_REGISTRY
typedef enum {
    TYPE_BOOL,
    TYPE_CHAR,
    TYPE_CHAR_ARR,
    TYPE_CHAR_PTR,
    TYPE_CONSTCHAR,
    TYPE_CONSTCHAR_PTR,
    TYPE_ENUM_ACCOUNTSTATE,
    TYPE_ENUM_PERMISSIONS,
    TYPE_POST_PTR,
    TYPE_SIZE_T,
    TYPE_STRUCT_POST,
    TYPE_STRUCT_USER,
    TYPE_STRUCT_USERPREFERNCES,
    TYPE_UINT32_T,
    TYPE_UINT64_T,
    TYPE_UNKNOWN,
} FieldType;

#include <cmyreflection.h>

/*
 * CMyReflection Active Plugins
 *  -> format (v1.0.0) by oonamo - Provides run time printing for primitive types
 *    - Provides tag: @no_print (Enums) - Forces the plugin to not generate get_field_as_str for enum
 *    - Provides tag: @format(value) (Struct Fields) - Specify a C format specifier for a struct.
 *      Does not create a get_field_as_str function if not defined
 *      Example:
 *      +  typedef struct {
 *      +      // cmy:format("my type: %x")
 *      +      int x;
 *      +  } MyStruct;
 *    - Provides tag: @display(value) (Enum Members) - Specifies how an enum should be displayed.
 *      Defaults to name of the enum member if not provided
 *      Example:
 *      +  typedef enum {
 *      +      // cmy:display("enum a")
 *      +      ENUM_A,
 *      +  } MyEnum;
 *    - Provides macro: CMY_HAS_FORMAT_PLUGIN (Value: 1) - format plugin is available
 *    - Provides macro: CMY_PLUGIN_FORMAT_ENABLED (Default: 1) - Enables the format plugin
 *    - Provides macro: CMY_FORMAT_MAX_BUF_LEN (Default: 256) - Default buffer len for printing (_MSC_VER)
 *    - Provides macro: CMY_PRINTF (Default: printf) - Defines the printf implementation
 *    - Provides router: ReflectResult get_field_as_str(..) - Creates a get_type_as_str for the type for primitives and enums
 *      By default, enums are enabled
 *      + Types: Permissions, AccountState, char_arr, char, uint32_t, bool,
 *        constchar*, char*, uint64_t, size_t
 *    - Provides function: ReflectResult print_field(...) - Prints a field, if it implements get_field_as_str
 *  -> json (v1.0.0) by oonamo - A json serializer plugin
 *    - Provides tag: @json_serialize_function(value) (Structs) - Function to call to serialize this type
 *      Example:
 *      +  @json_serialize_function(MyCoolStruct_Serializer)
 *      +  typedef struct { ... } MyCoolStruct;
 *      +  // in a seperate file
 *      +  #include "reflection.h"
 *      +  void MyCoolStruct_Serializer(const void* instance, const StructFieldInfo* field, _cmy_json_state* state);
 *    - Provides tag: @json_serialize_function(value) (Enums) - Function to call to serialize this type
 *      Example:
 *      +  @json_serialize_function(MyCoolEnum_Serializer)
 *      +  typedef enum { ... } MyCoolEnum;
 *      +  // in a seperate file
 *      +  #include "reflection.h"
 *      +  void MyCoolEnum_Serializer(const void* instance, const StructFieldInfo* field, _cmy_json_state* state);
 *    - Provides tag: @json_key_name(value) (Struct Fields) - Name of the json key
 *      Example:
 *      +  typedef struct
 *      +  {
 *      +      // cmy:json_key_name("new name")
 *      +      char* old_name;
 *      +  } MyType;
 *      Result:
 *      =  {
 *      =      "new name": "TYPE_CHAR_PTR"
 *      =  }
 *    - Provides macro: CMY_HAS_JSON_PLUGIN (Value: 1) - json plugin is available
 *    - Provides macro: CMY_PLUGIN_JSON_ENABLED (Default: 1) - Enables the json plugin
 *    - Provides macro: CMY_JSON_FMT_BUF_LEN (Default: 256) - Buffer length to use for custom format strings
 *    - Provides macro: CMY_JSON_DEBUG  - Adds debug information during certain operations
 *    - Provides macro: CMY_JSON_WRITE(state_ptr, ...) (Value: json_write_internal(state_ptr, __VA_ARGS__)) - Wrapper for json writing function
 *    - Provides router: ReflectResult json_serialize_custom(..) - Process fields dynamically based on their type
 *      + Types: Permissions
 *    - Provides router: bool json_is_string_type(..) - Checks if a type represents a string
 *      + Types: char_arr, constchar*, char*
 *    - Provides router: bool json_needs_quote(..) - Dynamically determines if the type requires JSON quotes
 *      + Types: Permissions, AccountState, char_arr, constchar*, char*
 *    - Provides router: bool json_is_string_array(..) - Determines if a type is an inline array
 *      + Types: char_arr
 *    - Provides function: void _fixed_buf_write_cb(...) - Internal fixed buffer callback wrapper
 *    - Provides function: void _json_traversal_iterator(...) - Json Traversal serializer
 *    - Provides function: void json_serialize_value(...) - Serialize a value into valid json
 *    - Provides function: void json_write_internal(...) - Internal Writing Function
 *    - Provides function: void json_write_string_escaped(...) - Safely escapes and streams strings
 *    - Provides function: ReflectResult to_json(...) - Converts a given type to a json string using a fixed buffer
 *    - Provides function: ReflectResult to_json_stream(...) - Converts a given type to a json string (streamed)
 */

#include <inttypes.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#define CMY_HAS_FORMAT_PLUGIN 1
#ifndef CMY_PLUGIN_FORMAT_ENABLED
#    define CMY_PLUGIN_FORMAT_ENABLED 1
#endif //CMY_PLUGIN_FORMAT_ENABLED
#ifndef CMY_FORMAT_MAX_BUF_LEN
#    define CMY_FORMAT_MAX_BUF_LEN 256
#endif //CMY_FORMAT_MAX_BUF_LEN
#ifndef CMY_PRINTF
#    define CMY_PRINTF printf
#endif //CMY_PRINTF
#define CMY_HAS_JSON_PLUGIN 1
#ifndef CMY_PLUGIN_JSON_ENABLED
#    define CMY_PLUGIN_JSON_ENABLED 1
#endif //CMY_PLUGIN_JSON_ENABLED
#ifndef CMY_JSON_FMT_BUF_LEN
#    define CMY_JSON_FMT_BUF_LEN 256
#endif //CMY_JSON_FMT_BUF_LEN
#ifndef CMY_JSON_DEBUG
    #ifdef NDEBUG
        #define CMY_JSON_DEBUG 1
    #else
        #define CMY_JSON_DEBUG 0
    #endif
#endif

#define CMY_JSON_WRITE(state_ptr, ...) json_write_internal(state_ptr, __VA_ARGS__)


// ----------------------------------------
// Generated by 'json'
// ----------------------------------------
typedef void (*cmy_json_write_cb)(const char* chunk, size_t len, void* user_ctx);

typedef struct
{
    char* _buf;
    size_t _capacity;
    size_t _current_offset;

    int indent;
    bool is_first_field;
    FIELD_TYPE current_parent_type;

    cmy_json_write_cb write_cb;
    void* cb_ctx;
} _cmy_json_state;

typedef struct
{
    char* buf;
    size_t capacity;
    size_t offset;
} _cmy_json_fixedbuf_ctx;


// ########################################
// format Declarations
// ########################################
#ifdef CMY_PLUGIN_FORMAT_ENABLED
static inline ReflectResult get_field_AccountState_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_Permissions_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_bool_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_char_arr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_char_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_conststr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_size_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_str_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_u32_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult get_field_u64_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen);
static inline ReflectResult print_field(const void* instance, const StructFieldInfo* field);
#endif // CMY_PLUGIN_FORMAT_ENABLED

// ########################################
// json Declarations
// ########################################
#ifdef CMY_PLUGIN_JSON_ENABLED
static void _fixed_buf_write_cb(const char* chunk, size_t len, void* user_ctx);
static inline void _json_traversal_iterator(const void            *base_instance,
                             const StructFieldInfo  *field,
                             void                   *user_data);
static inline bool json_is_string_array(FIELD_TYPE type);
static inline bool json_is_string_type(FIELD_TYPE type);
static inline bool json_needs_quote(FIELD_TYPE type);
static inline ReflectResult json_serialize_custom(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state);
static inline void json_serialize_value(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state);
static inline void json_write_internal(_cmy_json_state* state, const char* fmt, ...);
static inline void json_write_string_escaped(_cmy_json_state* state, const char* str);
extern ReflectResult serialize_permissions(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state);
static inline ReflectResult to_json(const void* instance, FIELD_TYPE root_type, char* out_buf, size_t buflen);
static inline ReflectResult to_json_stream(const void* instance, FIELD_TYPE root_type, cmy_json_write_cb write_cb, void* user_ctx);
#endif // CMY_PLUGIN_JSON_ENABLED


typedef struct {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
     const char* format;
#endif // CMY_PLUGIN_FORMAT_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
     char* json_key_name;
#endif // CMY_PLUGIN_JSON_ENABLED
} StructFieldExtension;

typedef struct {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
     const char* display;
#endif // CMY_PLUGIN_FORMAT_ENABLED
} EnumMemberExtension;
// --- Metadata Declarations
extern const StructFieldInfo Post_Metadata[];
extern const size_t Post_FieldCount;
extern const StructFieldInfo UserPrefernces_Metadata[];
extern const size_t UserPrefernces_FieldCount;
extern const StructFieldInfo User_Metadata[];
extern const size_t User_FieldCount;
extern const StructFieldExtension ext_User_username;
extern const StructFieldExtension ext_User_email;
extern const EnumMemberInfo Permissions_Members[];
extern const size_t Permissions_MemberCount;
extern const EnumMemberInfo AccountState_Members[];
extern const size_t AccountState_MemberCount;
extern const EnumMemberExtension ext_AccountState_ACCOUNT_ACTIVE;
extern const EnumMemberExtension ext_AccountState_ACCOUNT_INACTIVE;
extern const EnumMemberExtension ext_AccountState_ACCOUNT_STALE;

#define GET_FIELD_EXT(field_ptr) \
    ((field_ptr) && (field_ptr)->user_data ? (const StructFieldExtension*)((field_ptr)->user_data) : NULL)

#define GET_MEMBER_EXT(member_ptr) \
    ((member_ptr) && (member_ptr)->user_data ? ((const EnumMemberExtension*)(member_ptr->user_data)) : NULL)

// --- Auto-Generated Enum Validators ---

// Permissions is unchecked

static inline bool is_valid_AccountState(AccountState value) {
    switch(value) {
      case ACCOUNT_ACTIVE:
      case ACCOUNT_INACTIVE:
      case ACCOUNT_STALE:
           return true;
    default:
        return false;
    }
}

DEFINE_FIELD_SETTER(Permissions, TYPE_ENUM_PERMISSIONS, Permissions)
DEFINE_FIELD_GETTER(Permissions, TYPE_ENUM_PERMISSIONS, Permissions)

DEFINE_ENUM_SETTER(AccountState, TYPE_ENUM_ACCOUNTSTATE, AccountState, is_valid_AccountState)
DEFINE_FIELD_GETTER(AccountState, TYPE_ENUM_ACCOUNTSTATE, AccountState)

DEFINE_FIELD_SETTER(Post, TYPE_STRUCT_POST, Post)
DEFINE_FIELD_GETTER(Post, TYPE_STRUCT_POST, Post)

DEFINE_FIELD_SETTER(UserPrefernces, TYPE_STRUCT_USERPREFERNCES, UserPrefernces)
DEFINE_FIELD_GETTER(UserPrefernces, TYPE_STRUCT_USERPREFERNCES, UserPrefernces)

DEFINE_FIELD_SETTER(User, TYPE_STRUCT_USER, User)
DEFINE_FIELD_GETTER(User, TYPE_STRUCT_USER, User)

DEFINE_ARRAY_SETTER(char_arr, TYPE_CHAR_ARR, char *, char)
DEFINE_ARRAY_GETTER(char_arr, TYPE_CHAR_ARR, char *, char)

DEFINE_FIELD_SETTER(char, TYPE_CHAR, char)
DEFINE_FIELD_GETTER(char, TYPE_CHAR, char)

DEFINE_FIELD_SETTER(u32, TYPE_UINT32_T, uint32_t)
DEFINE_FIELD_GETTER(u32, TYPE_UINT32_T, uint32_t)

DEFINE_FIELD_SETTER(bool, TYPE_BOOL, bool)
DEFINE_FIELD_GETTER(bool, TYPE_BOOL, bool)

DEFINE_FIELD_SETTER(conststr, TYPE_CONSTCHAR_PTR, const char *)
DEFINE_FIELD_GETTER(conststr, TYPE_CONSTCHAR_PTR, const char *)

DEFINE_FIELD_SETTER(constchar, TYPE_CONSTCHAR, const char)
DEFINE_FIELD_GETTER(constchar, TYPE_CONSTCHAR, const char)

DEFINE_FIELD_SETTER(str, TYPE_CHAR_PTR, char       *)
DEFINE_FIELD_GETTER(str, TYPE_CHAR_PTR, char       *)

DEFINE_FIELD_SETTER(u64, TYPE_UINT64_T, uint64_t)
DEFINE_FIELD_GETTER(u64, TYPE_UINT64_T, uint64_t)

DEFINE_FIELD_SETTER(size_t, TYPE_SIZE_T, size_t)
DEFINE_FIELD_GETTER(size_t, TYPE_SIZE_T, size_t)

DEFINE_FIELD_SETTER(Post_ptr, TYPE_POST_PTR, Post *)
DEFINE_FIELD_GETTER(Post_ptr, TYPE_POST_PTR, Post *)

DEFINE_DYNAMIC_ARRAY_SETTER(User_posts, TYPE_POST_PTR, Post *, Post, TYPE_STRUCT_USER)
DEFINE_DYNAMIC_ARRAY_GETTER(User_posts, TYPE_POST_PTR, Post *, Post)

// --- Plugin-Generated-Extensions ---

// ==========================================
// Plugin: format
// ==========================================
#ifdef CMY_PLUGIN_FORMAT_ENABLED
static inline ReflectResult print_field(const void* instance, const StructFieldInfo* field)
{
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

#ifdef _MSC_VER
    size_t buflen = CMY_FORMAT_MAX_BUF_LEN;
    char buf[CMY_FORMAT_MAX_BUF_LEN];
#else // May have VLA support
    size_t buflen = field->count > 256 ? field->count : 256;
    char buf[buflen];
#endif

    ReflectResult res = get_field_as_str(instance, field, buf, buflen);
    if (res != REFLECT_OK) {
        return res;
    }

    CMY_PRINTF("%s", buf);
    return REFLECT_OK;
}

#endif // CMY_PLUGIN_FORMAT_ENABLED
#ifdef CMY_PLUGIN_FORMAT_ENABLED
static inline ReflectResult get_field_Permissions_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) {
        return REFLECT_ERR_NULL_PTR;
    }

    Permissions var;
    ReflectResult res = get_field_Permissions(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const EnumMetaData meta = EnumMetaData_FromName(Permissions);
    const char* enum_val = get_enum_member_name(meta.members, meta.count, (int)var);
    const EnumMemberInfo* info = (enum_val) ? Find_Enum_Member(meta, enum_val) : NULL;
    const EnumMemberExtension* ext = GET_MEMBER_EXT(info);

    const char* fmt = (ext && ext->display) ? ext->display : (enum_val ? enum_val : "<unknown>");
    snprintf(out_buf, buflen, "%s", fmt);
    return REFLECT_OK;
}

static inline ReflectResult get_field_AccountState_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) {
        return REFLECT_ERR_NULL_PTR;
    }

    AccountState var;
    ReflectResult res = get_field_AccountState(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const EnumMetaData meta = EnumMetaData_FromName(AccountState);
    const char* enum_val = get_enum_member_name(meta.members, meta.count, (int)var);
    const EnumMemberInfo* info = (enum_val) ? Find_Enum_Member(meta, enum_val) : NULL;
    const EnumMemberExtension* ext = GET_MEMBER_EXT(info);

    const char* fmt = (ext && ext->display) ? ext->display : (enum_val ? enum_val : "<unknown>");
    snprintf(out_buf, buflen, "%s", fmt);
    return REFLECT_OK;
}

static inline ReflectResult get_field_char_arr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) {
        return REFLECT_ERR_NULL_PTR;
    }

    #ifdef _MSC_VER
        if (field->count > CMY_FORMAT_MAX_BUF_LEN) { return REFLECT_ERR_OUT_OF_BOUNDS; }
        char var[CMY_FORMAT_MAX_BUF_LEN];;
    #else
        char var[field->count];
    #endif
    size_t arr_len = field->count;

    ReflectResult res = get_field_char_arr(instance, field, var, arr_len);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_char_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    char var;
    ReflectResult res = get_field_char(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%c";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_u32_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    uint32_t var;
    ReflectResult res = get_field_u32(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRIu32;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_bool_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) {
        return REFLECT_ERR_NULL_PTR;
    }

    bool var;
    ReflectResult res = get_field_bool(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);
    (void)ext;

    snprintf(out_buf, buflen, "%s", var ? "true" : "false");
    return REFLECT_OK;
}

static inline ReflectResult get_field_conststr_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    const char * var;
    ReflectResult res = get_field_conststr(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_str_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    char       * var;
    ReflectResult res = get_field_str(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%s";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_u64_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    uint64_t var;
    ReflectResult res = get_field_u64(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%" PRIu64;
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_size_t_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!instance || !field) { return REFLECT_ERR_NULL_PTR; }

    size_t var;
    ReflectResult res = get_field_size_t(instance, field, &var);;
    if (res != REFLECT_OK) {
        return res;
    }

    const StructFieldExtension* ext = GET_FIELD_EXT(field);

    const char* fmt = (ext && ext->format) ? ext->format : "%zu";
    snprintf(out_buf, buflen, fmt, var);
    return REFLECT_OK;
}

static inline ReflectResult get_field_as_str(const void* instance, const StructFieldInfo* field, char* out_buf, size_t buflen) {
    if (!field) { return REFLECT_ERR_NULL_PTR; }
    switch(field->type) {
        case TYPE_ENUM_PERMISSIONS: return get_field_Permissions_as_str(instance, field, out_buf, buflen);
        case TYPE_ENUM_ACCOUNTSTATE: return get_field_AccountState_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR_ARR: return get_field_char_arr_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR: return get_field_char_as_str(instance, field, out_buf, buflen);
        case TYPE_UINT32_T: return get_field_u32_as_str(instance, field, out_buf, buflen);
        case TYPE_BOOL: return get_field_bool_as_str(instance, field, out_buf, buflen);
        case TYPE_CONSTCHAR_PTR: return get_field_conststr_as_str(instance, field, out_buf, buflen);
        case TYPE_CHAR_PTR: return get_field_str_as_str(instance, field, out_buf, buflen);
        case TYPE_UINT64_T: return get_field_u64_as_str(instance, field, out_buf, buflen);
        case TYPE_SIZE_T: return get_field_size_t_as_str(instance, field, out_buf, buflen);
        default: return REFLECT_ERR_TYPE_MISMATCH;
    }
}

#endif // CMY_PLUGIN_FORMAT_ENABLED

// ==========================================
// Plugin: json
// ==========================================
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void json_serialize_value(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state)
{
    if (json_serialize_custom(exact_data_ptr, actual_type, field_ctx, state) == REFLECT_OK)
    {
        return;
    }

    StructMetaData meta;
    if (get_struct_metadata(actual_type, &meta) == REFLECT_OK) {
        CMY_JSON_WRITE(state, "{\n");

        _cmy_json_state nested_state = *state;
        nested_state.indent += 4;
        nested_state.is_first_field = true;
        nested_state.current_parent_type = actual_type;

        visit_struct_fields(exact_data_ptr, actual_type, _json_traversal_iterator, &nested_state);

        state->_current_offset = nested_state._current_offset;
        CMY_JSON_WRITE(state, "\n%*s}", state->indent, "");
        return;
    }

    if (exact_data_ptr && json_is_string_type(actual_type)) {
        const StructFieldExtension* ext = GET_FIELD_EXT(field_ctx);
        const char* fmt = (ext && ext->format) ? ext->format : "%s";

        StructFieldInfo element_field = {0};
        if (field_ctx) {
            element_field = *field_ctx;
            element_field.offset = 0;

            if (!json_is_string_array(actual_type)) {
                element_field.count = 0;
            }
        }

        // Default
        if (strcmp(fmt, "%s") == 0) {
            const char* str_ptr = NULL;

            // exact_data_ptr is ptr to static array
            if (json_is_string_array(actual_type)) {
                str_ptr = (const char*)exact_data_ptr;
            } else {
                get_field_value(exact_data_ptr, &element_field, (void*)&str_ptr, sizeof(const char*));
            }

            json_write_string_escaped(state, str_ptr);
        } else {
            char fmt_buf[CMY_JSON_FMT_BUF_LEN];
            if (field_ctx) {
                get_field_as_str(exact_data_ptr, &element_field, fmt_buf, sizeof(fmt_buf));
            }
            json_write_string_escaped(state, fmt_buf);
        }
        return;
    }

    char val_buf[256] = "null";
    bool force_quotes = false;
    bool is_explicit_null = false;

    if (exact_data_ptr && field_ctx) {
        StructFieldInfo element_field = *field_ctx;
        element_field.type = actual_type;
        element_field.offset = 0;

        if (!json_is_string_type(actual_type)) {
            element_field.count = 1;
        }

        if (get_field_as_str(exact_data_ptr, &element_field, val_buf, sizeof(val_buf)) != REFLECT_OK) {
#if CMY_JSON_DEBUG
            snprintf(val_buf, sizeof(val_buf), "<unsupported: %s at %p>", get_name_of_type(actual_type), exact_data_ptr);
#else
            snprintf(val_buf, sizeof(val_buf), "<unsupported: %s>", get_name_of_type(actual_type));
#endif
            force_quotes = true;
        }
        else if (strcmp(val_buf, "(null)") == 0) {
            snprintf(val_buf, sizeof(val_buf), "null");
            is_explicit_null = true;
        }
    } else {
        snprintf(val_buf, sizeof(val_buf), "%s", get_name_of_type(actual_type));
    }

    if (force_quotes || !exact_data_ptr || (json_needs_quote(actual_type) && !is_explicit_null)) {
        CMY_JSON_WRITE(state, "\"%s\"", val_buf);
    } else {
        CMY_JSON_WRITE(state, "%s", val_buf);
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void json_write_internal(_cmy_json_state* state, const char* fmt, ...)
{
    char scratch[128];

    va_list args;
    va_start(args, fmt);
    int written = vsnprintf(scratch, sizeof(scratch), fmt, args);
    va_end(args);

    if (written < 0) { return; }

    size_t len_to_write = ((size_t)written < sizeof(scratch)) ? (size_t)written : sizeof(scratch) - 1;

    state->write_cb(scratch, len_to_write, state->cb_ctx);
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void _json_traversal_iterator(const void            *base_instance,
                             const StructFieldInfo  *field,
                             void                   *user_data)
{
    if (!field || !(field->flags & FIELD_ACCESS_READ)) { return; }

    _cmy_json_state *state = (_cmy_json_state*)user_data;
    if (!state->is_first_field) {
        CMY_JSON_WRITE(state, ",\n");
    } else {
        state->is_first_field = false;
    }

    // Print Key
    const StructFieldExtension* ext = GET_FIELD_EXT(field);
    const char* key = (ext && ext->json_key_name) ? ext->json_key_name : field->name;
    CMY_JSON_WRITE(state, "%*s\"%s\": ", state->indent, "", key);

    bool is_string = json_is_string_type(field->type);
    bool is_dynamic = field->length_field_name != NULL;
    bool is_arr = (is_dynamic || (field->count > 1)) && !is_string;

    if (is_arr) {
        if (!base_instance) {
            const char* type_name = get_name_of_type(get_base_type(field->type));
            if (is_dynamic) {
                CMY_JSON_WRITE(state, "[\"%s (dynamic: %s)\"]", type_name, field->length_field_name);
            } else if (is_arr) {
                CMY_JSON_WRITE(state, "[\"%s (max: %zu)\"]", type_name, field->count);
            }
            return;
        }

        size_t array_len = 0;
        const void* array_ptr = NULL;
        FIELD_TYPE base_type = get_base_type(field->type);
        size_t base_size = get_type_size(base_type);

        if (is_dynamic) {
            if (get_dynamic_array_length(base_instance, state->current_parent_type, field, &array_len) != REFLECT_OK) {
                CMY_JSON_WRITE(state, "null");
                return;
            }
            if (get_field_value(base_instance, field, (void*)&array_ptr, sizeof(void*)) != REFLECT_OK)
            {
                CMY_JSON_WRITE(state, "null");
                return;
            }
        } else {
            array_len = field->count;
            array_ptr = (const char*)base_instance + field->offset;
        }

        CMY_JSON_WRITE(state, "[\n");
        _cmy_json_state arr_state = *state;
        arr_state.indent += 4;

        for (size_t i = 0; i < array_len; i++)
        {
            CMY_JSON_WRITE(&arr_state, "%*s", arr_state.indent, "");
            void* ith_element = (char*)array_ptr + (i * base_size);

            if (!ith_element) {
                CMY_JSON_WRITE(&arr_state, "null");
            } else {
                json_serialize_value(ith_element, base_type, field, &arr_state);
            }

            if (i < array_len - 1) {
                CMY_JSON_WRITE(&arr_state, ",\n");
            } else {
                CMY_JSON_WRITE(&arr_state, "\n");
            }
        }
        state->_current_offset = arr_state._current_offset;
        CMY_JSON_WRITE(state, "%*s]", state->indent, "");

        return;
    } else {
        const void* data_ptr = base_instance ? ((const char*)base_instance + field->offset) : NULL;
        json_serialize_value(data_ptr, field->type, field, state);
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static void _fixed_buf_write_cb(const char* chunk, size_t len, void* user_ctx)
{
    _cmy_json_fixedbuf_ctx* mem = (_cmy_json_fixedbuf_ctx*)user_ctx;

    size_t available = mem->capacity - mem->offset - 1;
    if (available == 0) return;

    size_t to_write = (len < available) ? len : available;

    memcpy(mem->buf + mem->offset, chunk, to_write);
    mem->offset += to_write;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline void json_write_string_escaped(_cmy_json_state* state, const char* str)
{
    if (!str) {
        state->write_cb("null", 4, state->cb_ctx);
        return;
    }

    state->write_cb("\"", 1, state->cb_ctx);

    const char* p = str;
    while (*p) {
        switch(*p) {
            case '"':  state->write_cb("\\\"", 2, state->cb_ctx); break;
            case '\\': state->write_cb("\\\\", 2, state->cb_ctx); break;
            case '\b': state->write_cb("\\b",  2, state->cb_ctx); break;
            case '\f': state->write_cb("\\f",  2, state->cb_ctx); break;
            case '\n': state->write_cb("\\n",  2, state->cb_ctx); break;
            case '\r': state->write_cb("\\r",  2, state->cb_ctx); break;
            case '\t': state->write_cb("\\t", 2, state->cb_ctx); break;
            default:   state->write_cb(p, 1, state->cb_ctx); break;
        }
        p++;
    }

    state->write_cb("\"", 1, state->cb_ctx);
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline ReflectResult to_json_stream(const void* instance, FIELD_TYPE root_type, cmy_json_write_cb write_cb, void* user_ctx)
{
    if (!write_cb) { return REFLECT_ERR_NULL_PTR; }

    _cmy_json_state state = {
        .indent = 0,
        .is_first_field = true,
        .current_parent_type = root_type,
        .write_cb = write_cb,
        .cb_ctx = user_ctx,
    };

    json_serialize_value(instance, root_type, NULL, &state);

    return REFLECT_OK;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED

static inline ReflectResult to_json(const void* instance, FIELD_TYPE root_type, char* out_buf, size_t buflen)
{
    if (!out_buf || buflen == 0) { return REFLECT_ERR_NULL_PTR; }

    _cmy_json_fixedbuf_ctx ctx = {
        .buf = out_buf,
        .capacity = buflen,
        .offset = 0
    };

    ReflectResult res = to_json_stream(instance, root_type, _fixed_buf_write_cb, &ctx);

    ctx.buf[ctx.offset] = '\0';

    return res;
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline ReflectResult json_serialize_custom(const void* exact_data_ptr, FIELD_TYPE actual_type, const StructFieldInfo* field_ctx, _cmy_json_state* state) {
    
    switch(actual_type) {
        case TYPE_ENUM_PERMISSIONS: return serialize_permissions(exact_data_ptr, actual_type, field_ctx, state);
        default: return REFLECT_ERR_TYPE_MISMATCH;
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline bool json_is_string_type(FIELD_TYPE type) {
    
    switch(type) {
        case TYPE_CHAR_ARR: return true;
        case TYPE_CONSTCHAR_PTR: return true;
        case TYPE_CHAR_PTR: return true;
        default: return false;
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline bool json_needs_quote(FIELD_TYPE type) {
    
    switch(type) {
        case TYPE_ENUM_PERMISSIONS: return true;
        case TYPE_ENUM_ACCOUNTSTATE: return true;
        case TYPE_CHAR_ARR: return true;
        case TYPE_CONSTCHAR_PTR: return true;
        case TYPE_CHAR_PTR: return true;
        default: return false;
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED
#ifdef CMY_PLUGIN_JSON_ENABLED
static inline bool json_is_string_array(FIELD_TYPE type) {
    
    switch(type) {
        case TYPE_CHAR_ARR: return true;
        default: return false;
    }
}

#endif // CMY_PLUGIN_JSON_ENABLED

#endif // CMYREFLECTION_AUTOGEN_H
// --- Metadata Definitions
#ifdef REFLECTION_IMPLEMENTATION

// --- Generated from types.h ---
const StructFieldInfo Post_Metadata[] = {
    { "title", TYPE_CHAR_ARR, offsetof(Post, title), sizeof(char[MAX_TITLE_LEN]), MAX_TITLE_LEN, FIELD_ACCESS_RW, NULL, NULL },
    { "likes", TYPE_UINT32_T, offsetof(Post, likes), sizeof(uint32_t), 1, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t Post_FieldCount = sizeof(Post_Metadata) / sizeof(StructFieldInfo);

const StructFieldInfo UserPrefernces_Metadata[] = {
    { "language", TYPE_CHAR_ARR, offsetof(UserPrefernces, language), sizeof(char[32]), 32, FIELD_ACCESS_RW, NULL, NULL },
    { "prefers_dark", TYPE_BOOL, offsetof(UserPrefernces, prefers_dark), sizeof(bool), 1, FIELD_ACCESS_RW, NULL, NULL },
};
const size_t UserPrefernces_FieldCount = sizeof(UserPrefernces_Metadata) / sizeof(StructFieldInfo);

const StructFieldExtension ext_User_username = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.format = "%s",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};
const StructFieldExtension ext_User_email = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.format = "%s",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};

const StructFieldInfo User_Metadata[] = {
    { "username", TYPE_CHAR_ARR, offsetof(User, username), sizeof(char[32]), 32, FIELD_ACCESS_RW, NULL, (void*)&ext_User_username },
    { "email", TYPE_CHAR_ARR, offsetof(User, email), sizeof(char[64]), 64, FIELD_ACCESS_RW, NULL, (void*)&ext_User_email },
    { "name", TYPE_CONSTCHAR_PTR, offsetof(User, name), sizeof(const char *), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "str", TYPE_CHAR_PTR, offsetof(User, str), sizeof(char       *), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "account_id", TYPE_UINT64_T, offsetof(User, account_id), sizeof(uint64_t), 1, FIELD_ACCESS_READ, NULL, NULL },
    { "password_hash", TYPE_CHAR_ARR, offsetof(User, password_hash), sizeof(char[64]), 64, FIELD_ACCESS_WRITE, NULL, NULL },
    { "permissions", TYPE_ENUM_PERMISSIONS, offsetof(User, permissions), sizeof(Permissions), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "state", TYPE_ENUM_ACCOUNTSTATE, offsetof(User, state), sizeof(AccountState), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "settings", TYPE_STRUCT_USERPREFERNCES, offsetof(User, settings), sizeof(UserPrefernces), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "post_count", TYPE_SIZE_T, offsetof(User, post_count), sizeof(size_t), 1, FIELD_ACCESS_RW, NULL, NULL },
    { "posts", TYPE_POST_PTR, offsetof(User, posts), sizeof(Post *), 1, FIELD_ACCESS_RW, "post_count", NULL },
};
const size_t User_FieldCount = sizeof(User_Metadata) / sizeof(StructFieldInfo);

const EnumMemberInfo Permissions_Members[] = {
   { PERM_CREATE, "PERM_CREATE", NULL },
   { PERM_DELETE, "PERM_DELETE", NULL },
   { PERM_UPDATE, "PERM_UPDATE", NULL },
};
const size_t Permissions_MemberCount = sizeof(Permissions_Members) / sizeof(EnumMemberInfo);

const EnumMemberExtension ext_AccountState_ACCOUNT_ACTIVE = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.display = "Active",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};
const EnumMemberExtension ext_AccountState_ACCOUNT_INACTIVE = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.display = "Inactive",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};
const EnumMemberExtension ext_AccountState_ACCOUNT_STALE = {
#ifdef CMY_PLUGIN_FORMAT_ENABLED
.display = "Stale",
#endif // CMY_PLUGIN_FORMAT_ENABLED
};
const EnumMemberInfo AccountState_Members[] = {
   { ACCOUNT_ACTIVE, "ACCOUNT_ACTIVE", (void*)&ext_AccountState_ACCOUNT_ACTIVE },
   { ACCOUNT_INACTIVE, "ACCOUNT_INACTIVE", (void*)&ext_AccountState_ACCOUNT_INACTIVE },
   { ACCOUNT_STALE, "ACCOUNT_STALE", (void*)&ext_AccountState_ACCOUNT_STALE },
};
const size_t AccountState_MemberCount = sizeof(AccountState_Members) / sizeof(EnumMemberInfo);

// --- Auto-Generated Type Registry
ReflectResult get_struct_metadata(FieldType type, StructMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_STRUCT_POST:
          out_meta->fields = Post_Metadata;
          out_meta->count = Post_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_USERPREFERNCES:
          out_meta->fields = UserPrefernces_Metadata;
          out_meta->count = UserPrefernces_FieldCount;
          return REFLECT_OK;
      case TYPE_STRUCT_USER:
          out_meta->fields = User_Metadata;
          out_meta->count = User_FieldCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated Type Registry
ReflectResult get_enum_metadata(FieldType type, EnumMetaData* out_meta) {
    if (!out_meta) return REFLECT_ERR_NULL_PTR;
    switch(type) {
      case TYPE_ENUM_PERMISSIONS:
          out_meta->members = Permissions_Members;
          out_meta->count = Permissions_MemberCount;
          return REFLECT_OK;
      case TYPE_ENUM_ACCOUNTSTATE:
          out_meta->members = AccountState_Members;
          out_meta->count = AccountState_MemberCount;
          return REFLECT_OK;
        default: return REFLECT_ERR_ENUM_INVALID;
    }
}


// --- Auto-Generated Safe Type Setter
ReflectResult safe_set_field(void* instance, const StructFieldInfo* field, const void* value, size_t element_count) {
    if (!instance || !field || !value) return false;
    switch(field->type) {
      case TYPE_ENUM_PERMISSIONS: return set_field_Permissions(instance, field, *(Permissions*)value);
      case TYPE_ENUM_ACCOUNTSTATE: return set_field_AccountState(instance, field, *(AccountState*)value);
      case TYPE_STRUCT_POST: return set_field_Post(instance, field, *(Post*)value);
      case TYPE_STRUCT_USERPREFERNCES: return set_field_UserPrefernces(instance, field, *(UserPrefernces*)value);
      case TYPE_STRUCT_USER: return set_field_User(instance, field, *(User*)value);
      case TYPE_CHAR_ARR: return set_field_char_arr(instance, field, (char*)value, element_count);
      case TYPE_CHAR: return set_field_char(instance, field, *(char*)value);
      case TYPE_UINT32_T: return set_field_u32(instance, field, *(uint32_t*)value);
      case TYPE_BOOL: return set_field_bool(instance, field, *(bool*)value);
      case TYPE_CONSTCHAR_PTR: return set_field_conststr(instance, field, *(const char **)value);
      case TYPE_CONSTCHAR: return set_field_constchar(instance, field, *(const char*)value);
      case TYPE_CHAR_PTR: return set_field_str(instance, field, *(char       **)value);
      case TYPE_UINT64_T: return set_field_u64(instance, field, *(uint64_t*)value);
      case TYPE_SIZE_T: return set_field_size_t(instance, field, *(size_t*)value);
      case TYPE_POST_PTR: return set_field_Post_ptr(instance, field, *(Post **)value);
        default: return REFLECT_ERR_TYPE_INVALID;
    }
}

// --- Auto-Generated enum->name converter
const char* get_name_of_type(FieldType type) {
    switch(type) {
     case TYPE_BOOL: return "TYPE_BOOL";
     case TYPE_CHAR: return "TYPE_CHAR";
     case TYPE_CHAR_ARR: return "TYPE_CHAR_ARR";
     case TYPE_CHAR_PTR: return "TYPE_CHAR_PTR";
     case TYPE_CONSTCHAR: return "TYPE_CONSTCHAR";
     case TYPE_CONSTCHAR_PTR: return "TYPE_CONSTCHAR_PTR";
     case TYPE_ENUM_ACCOUNTSTATE: return "TYPE_ENUM_ACCOUNTSTATE";
     case TYPE_ENUM_PERMISSIONS: return "TYPE_ENUM_PERMISSIONS";
     case TYPE_POST_PTR: return "TYPE_POST_PTR";
     case TYPE_SIZE_T: return "TYPE_SIZE_T";
     case TYPE_STRUCT_POST: return "TYPE_STRUCT_POST";
     case TYPE_STRUCT_USER: return "TYPE_STRUCT_USER";
     case TYPE_STRUCT_USERPREFERNCES: return "TYPE_STRUCT_USERPREFERNCES";
     case TYPE_UINT32_T: return "TYPE_UINT32_T";
     case TYPE_UINT64_T: return "TYPE_UINT64_T";
     case TYPE_UNKNOWN: return "TYPE_UNKNOWN";
        default: return NULL;
    };
}

FieldType get_base_type(FieldType type) {
    switch(type) {
      case TYPE_CHAR_ARR: return TYPE_CHAR;
      case TYPE_CONSTCHAR_PTR: return TYPE_CONSTCHAR;
      case TYPE_CHAR_PTR: return TYPE_CHAR;
      case TYPE_POST_PTR: return TYPE_STRUCT_POST;
        default: return type;
    }
}

size_t get_type_size(FIELD_TYPE type) {
    switch(type) {
        case TYPE_ENUM_PERMISSIONS: return sizeof(Permissions);
        case TYPE_ENUM_ACCOUNTSTATE: return sizeof(AccountState);
        case TYPE_STRUCT_POST: return sizeof(Post);
        case TYPE_STRUCT_USERPREFERNCES: return sizeof(UserPrefernces);
        case TYPE_STRUCT_USER: return sizeof(User);
        case TYPE_CHAR_ARR: return sizeof(char *);
        case TYPE_CHAR: return sizeof(char);
        case TYPE_UINT32_T: return sizeof(uint32_t);
        case TYPE_BOOL: return sizeof(bool);
        case TYPE_CONSTCHAR_PTR: return sizeof(const char *);
        case TYPE_CONSTCHAR: return sizeof(const char);
        case TYPE_CHAR_PTR: return sizeof(char       *);
        case TYPE_UINT64_T: return sizeof(uint64_t);
        case TYPE_SIZE_T: return sizeof(size_t);
        case TYPE_POST_PTR: return sizeof(Post *);
        default: return 0;
    }
}
#endif // REFLECTION_IMPLEMENTATION
#ifdef _MSC_VER
  #pragma warning(pop)
#endif

